<div class="content">
    <h3 class="text-light">Envoi d’un nouveau média</h3>

    <div class="outer mt-25px">
        <div class="panel">
            <div class="span12">
                <div class="widget">

                    <script type="text/javascript" src="<?php echo THEMES_TRANO_URL ?>js/jquery.min.js"></script>

                    <?php 
                        Application_Class_Forms::mediamultipleUpload(
                            'file-uploader'
                            ,'folder=medias'
                        ); 
                    ?>
                </div>
            </div>

        </div>
    </div>
</div>
