<input type="hidden" id="id_item" name="id_item" value="<?php echo $this->id_item; ?>">
<input type="hidden" id="module" name="module" value="<?php echo $this->module; ?>">
<input type="hidden" id="type" name="type" value="<?php echo $this->type; ?>">

<div class="media-frame-title">
	<h1><?php echo $this->translate("Mettre une image à la Une"); ?><span class="dashicons dashicons-arrow-down"></span></h1>
</div>

<div class="media-frame-router">
	<div class="widget">
	    <div class="tabbable">
	        <ul class="nav nav-tabs">
	            <li class=""><a href="#tab1" data-toggle="tab"><?php echo $this->translate("Envoyer des fichiers"); ?></a></li>
	            <li class="active"><a href="#tab2" data-toggle="tab"><?php echo $this->translate("Bibliothèque de médias"); ?></a></li>
	        </ul>
	    </div>
	</div>
</div>

<div class="media-frame-content media-frame">
	<div class="attachments-browser">
		<div class="tab-content">
		    <div class="tab-pane" id="tab1">Tab 1</div>
		    <div class="tab-pane active" id="tab2">
		    	<div class="gallery-image-view">
		    		<ul class="attachments reorder_ul reorder-photos-list ui-sortable">

                        <?php 
                        $media_id = NULL;
                        if(!empty($this->medias)){
                            foreach ($this->medias as $k => $media) {
                                $media_id = (int)$media['media_id'];
                                $media_url = Application_Model_Media::getUrlById($media_id);

                                $current = '';
                                if($k==0 && !$this->id_media){
                                    $current = 'current';
                                    $media_id_current = $media_id;
                                }
                                if($media_id==$this->id_media){
                                    $current = 'current';
                                    $media_id_current = $media_id;
                                }
                        ?>
            				        <li data-module="media" id="<?php echo $media_id; ?>" class="ui-sortable-handle <?php echo $current; ?>">
                                        <a href="javascript:void(0);" style="float:none;" class="image_link">
                                            <div class="wrap">
                                                <i style="background-image: url(<?php echo $media_url; ?>);"></i>
                                            </div>
                                        </a>
                                    </li>				
                        <?php 
                                }
                            } 
                        ?>
		    		</ul>
		    	</div>
		    	<div class="media-sidebar">
                    <?php echo $this->partial("medias/sidebar/media_metas.phtml", array("media_id"=>$media_id_current)); ?>
		    	</div>
		    </div>
		</div>
	</div>
</div>

<div class="media-frame-toolbar">
	<div class="media-toolbar">
		<div class="media-toolbar-secondary"></div>
		<div class="media-toolbar-primary search-form">
			<a id="addImage" style="cursor:pointer" class="btn btn-info media-button-select"><?php echo $this->translate("Mettre une image à la Une"); ?></a>
		</div>
	</div>
</div>