<?php 
	$id = Application_Class_Utils::idx($this->media, 'id', 0); 

	$media_data      = Application_Model_Media::getMediaData($id);
	$media_width     = $media_data['width'];
	$media_height    = $media_data['height'];
	$media_filesize  = $media_data['filesize'];
	$media_extension = Application_Model_Media::getMediaExtension($id);
	$media_url       = Application_Model_Media::getUrlById($id);
?>
<div class="content">
    <h3 class="text-light">Média</h3>

    <div class="outer mt-25px">
        <div class="panel">
	        <form method="post" action="" id="images-form" class="form-horizontal form-to-validate">
	            <input type="hidden" value="<?php echo $id; ?>" id="id" name="Medias[id]">
	          
		    	<div class="row-fluid">
			    	<div class="span9">
                        <div class="well">
                            <div class="tabbable">
                                <?php Application_Class_Snippets::multilingualTabs(); ?>
                                
                                <div class="well tab-form-content">
                                    <div class="control-group">
                                        <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Titre"); ?>:</label>
                                        <div class="controls" style="margin-top: 5px">
                                            <?php 
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id'            => 'title'
                                                        ,'autocomplete' => 'off'
                                                    )
                                                    ,'custom' => array(
                                                        'class'        => 'validate[required] span12 multilingual'
                                                        ,'module'      => 'Medias'
                                                        ,'name'        => 'title'
                                                        ,'data'        => $this->media
                                                    )
                                                );
                                                Application_Class_Forms::textMultilingual($attributes); 
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="title"> <?php echo $this->translate("Image"); ?>:</label>
                                        <div class="controls">
                                            <?php 
                                                $image_url = Application_Model_Media::getUrlById($this->id);
                                                if($image_url){
                                                    echo '<img style="max-width:100%" src="'.$image_url.'" />';
                                                }else{
                                                    echo $this->view->translate("Média introuvable");
                                                }
                                            ?>
                                        </div>
                                    </div>                          

                                    <div class="control-group">
                                        <label class="control-label" for="caption"> <?php echo $this->translate("Légende"); ?>:</label>
                                        <div class="controls">
                                            <?php 
                                                $attributes = array(
                                                    'classic' => array(
                                                        'autocomplete' => 'off'
                                                        ,'rows'        => 5
                                                    )
                                                    ,'custom' => array(
                                                        'id'           => 'caption'
                                                        ,'class'       => 'span12 multilingual'
                                                        ,'module'      => 'Medias'
                                                        ,'name'        => 'caption'
                                                        ,'data'        => $this->media
                                                    )
                                                );
                                                Application_Class_Forms::textareaMultilingual($attributes);
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="alt"> <?php echo $this->translate("Texte alternatif"); ?>:</label>
                                        <div class="controls">
                                            <?php 
                                                $attributes = array(
                                                    'classic' => array(
                                                        'id'            => 'alt'
                                                        ,'autocomplete' => 'off'
                                                    )
                                                    ,'custom' => array(
                                                        'class'        => 'span12 multilingual'
                                                        ,'module'      => 'Medias'
                                                        ,'name'        => 'alt'
                                                        ,'data'        => $this->media
                                                    )
                                                );
                                                Application_Class_Forms::textMultilingual($attributes); 
                                            ?>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="description"> <?php echo $this->translate("Description"); ?>:</label>
                                        <div class="controls">
                                            <?php 
                                                $attributes = array(
                                                    'classic' => array(
                                                        'autocomplete' => 'off'
                                                        ,'rows'        => 10
                                                    )
                                                    ,'custom' => array(
                                                        'id'           => 'description'
                                                        ,'class'       => 'span12 multilingual ckeditor'
                                                        ,'module'      => 'Medias'
                                                        ,'name'        => 'description'
                                                        ,'data'        => $this->media
                                                    )
                                                );
                                                Application_Class_Forms::textareaMultilingual($attributes); 
                                                Application_Class_Ckeditor::initToggleCkeditorBasic('description');
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
				    </div>

				    <div class="span3">
			    	    <div class="well">
			    	    	<div class="navbar">
			    		        <div class="navbar-inner">
			    		            <h6><?php echo $this->translate("Enregister"); ?></h6>
			    		        </div>
			    		    </div>

			    		    <table class="table table-striped no-border">
                                    <tbody>
                                        <tr><td><?php echo $this->translate("Mise en ligne le"); ?> : <strong><?php echo $this->media['create_time']; ?></strong></td></tr>
                                        <tr><td><?php echo $this->translate("Dernière mise à jour le"); ?> : <strong><?php echo $this->media['update_time']; ?></strong></td></tr>
                                        <tr>
                                            <td>
                                                <?php echo $this->translate("Adresse web du fichier"); ?> : <br/>
                                                <div class="input-append" style="width:75%">
                                                    <input id="appendedInputButton" class="span12 input-block-level" type="text" value="<?php echo $media_url; ?>" />
                                                    <a class="btn" href="<?php echo $media_url; ?>" target="_blank"><?php echo $this->translate("Voir"); ?></a>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr><td><?php echo $this->translate("Nom du fichier"); ?> : <strong><?php echo $this->media['filename']; ?></strong></td></tr>
                                        <tr><td><?php echo $this->translate("Type du fichier"); ?> : <strong>.<?php echo $media_extension; ?></strong></td></tr>
                                        <tr><td><?php echo $this->translate("Taille du fichier"); ?> : <strong><?php echo $media_filesize; ?></strong></td></tr>
                                        <tr><td><?php echo $this->translate("Dimensions"); ?> : <strong><?php echo $media_width; ?> x <?php echo $media_height; ?></strong></td></tr>
                                    </tbody>
                                </table>

                            
                                <div class="form-actions">
                                    <button id="save" class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                                    <button type="button" class="btn btn-danger ml5" onclick="window.location.href='<?php echo $this->baseUrl() ?>/medias'"><?php echo $this->translate("Retour"); ?></button>
                                </div>
			    		</div>

				    </div>
				</div>
	        </form>
        </div>
    </div>
</div>