<!--Events Section-->
<section class="events-section" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/2.jpg);">
  <div class="auto-container">
      <!--Sec Title-->
        <div class="sec-title light centered">
          <div class="title">Participate With Us</div>
          <h2>Upcoming Events</h2>
        </div>
        <!--Events Carousel-->
        <div class="events-carousel owl-carousel owl-theme">
        
          <!--Event Block-->
          <div class="event-block">
              <div class="inner-box clearfix">
                  <!--Image Column-->
                  <div class="image-column col-md-6 col-sm-12 col-xs-12">
                      <div class="image">
                          <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-2.jpg" alt="" />
                        </div>
                    </div>
                    <!--Content Column-->
                  <div class="content-column col-md-6 col-sm-12 col-xs-12">
                      <div class="inner">
                          <h3><a href="#">International Day of Forests</a></h3>
                            <div class="post-date">Held on <span>August 14, 2107</span></div>
                            <div class="text">To celebrate the ways in which forests and trees sustain and protect us. Torem ipsum dolors amet consectetur adipisicing elit sed eiusmod tempor incididunt labore et dolore magna aliqua. </div>
                            <a href="#" class="view-detail">View Details &nbsp;<span class="flaticon-login"></span></a>
                            <ul class="post-meta">
                              <li><span class="icon flaticon-pin"></span>Melbourne, Victoria, 123 Kings Street</li>
                                <li><span class="icon flaticon-clock"></span>From 9.00 am to 5.00 pm</li>
                            </ul>
          </div>
                    </div>
                </div>
            </div>
          <!--Event Block-->
            
            
            <!--Event Block-->
          <div class="event-block">
              <div class="inner-box clearfix">
                  <!--Image Column-->
                  <div class="image-column col-md-6 col-sm-12 col-xs-12">
                      <div class="image">
                          <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-2.jpg" alt="" />
                        </div>
                    </div>
                    <!--Content Column-->
                  <div class="content-column col-md-6 col-sm-12 col-xs-12">
                      <div class="inner">
                          <h3><a href="#">Time to Grow Forests</a></h3>
                            <div class="post-date">Held on <span>August 14, 2107</span></div>
                            <div class="text">To celebrate the ways in which forests and trees sustain and protect us. Torem ipsum dolors amet consectetur adipisicing elit sed eiusmod tempor incididunt labore et dolore magna aliqua. </div>
                            <a href="#" class="view-detail">View Details &nbsp;<span class="flaticon-login"></span></a>
                            <ul class="post-meta">
                              <li><span class="icon flaticon-pin"></span>Melbourne, Victoria, 268 Vulcans Street</li>
                                <li><span class="icon flaticon-clock"></span>From 9.00 am to 5.00 pm</li>
                            </ul>
          </div>
                    </div>
                </div>
            </div>
          <!--Event Block-->
            
            <!--Event Block-->
          <div class="event-block">
              <div class="inner-box clearfix">
                  <!--Image Column-->
                  <div class="image-column col-md-6 col-sm-12 col-xs-12">
                      <div class="image">
                          <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-2.jpg" alt="" />
                        </div>
                    </div>
                    <!--Content Column-->
                  <div class="content-column col-md-6 col-sm-12 col-xs-12">
                      <div class="inner">
                          <h3><a href="#">Last Days of Forests </a></h3>
                            <div class="post-date">Held on <span>August 14, 2107</span></div>
                            <div class="text">To celebrate the ways in which forests and trees sustain and protect us. Torem ipsum dolors amet consectetur adipisicing elit sed eiusmod tempor incididunt labore et dolore magna aliqua. </div>
                            <a href="#" class="view-detail">View Details &nbsp;<span class="flaticon-login"></span></a>
                            <ul class="post-meta">
                              <li><span class="icon flaticon-pin"></span>New York, USA, 532 Hypo Street</li>
                                <li><span class="icon flaticon-clock"></span>From 9.00 am to 5.00 pm</li>
                            </ul>
          </div>
                    </div>
                </div>
            </div>
          <!--Event Block-->
            
        </div>
    </div>
</section>
<!--End Events Section-->
