<!--FullWidth Section-->
<section class="fullwidth-section">
	<div class="section-outer clearfix">
    	<div class="image-column" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/resource/image-1.jpg);">
        	<div class="hidden-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-1.jpg" alt=""></div>
        </div>
        <div class="content-column">
        	<div class="content">
            	<div class="title">Work for the Cause</div>
                <h2>Become Saviour Of The Planet Earth</h2>
                <div class="text">Labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea com modo conse quat. Duis aute irure dolor in reprehenderit ein voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim.</div>
                <div class="category"><span>Event:</span> Save Plants & Trees</div>
                
                <div class="donate-bar wow fadeIn" data-wow-delay="0ms" data-wow-duration="0ms">
                    <div class="bar-inner">
                    	<div class="bar" style="width:80%;"><div class="count-box"><span class="count-text" data-speed="2000" data-stop="80"></span></div></div>
                    </div>
                </div>
                <!--donate info-->
                <div class="donate-info clearfix">
                    <div class="amount raised">Raised  $67,050</div>
                    <div class="amount goal">Goal  $75,000</div>
                </div>
                <br>
                <br><br>
                <a href="#" class="theme-btn btn-style-three">Join Now</a>&ensp;&ensp;<a href="donate.html" class="theme-btn btn-style-one">donate us</a>
            </div>
        </div>
	</div>
</section>
<!--End FullWidth Section-->
