<!--Project Section-->
<section class="project-section">
	<div class="auto-container">
    
    	<!--Porfolio Tabs-->
        <div class="project-tab">
            <!--Sec Title-->
            <div class="sec-title clearfix">
            	
                <div class="pull-left">
                    <div class="title">Reasons to Help Us</div>
                    <h2>Recent Projects</h2>
                </div>
                
                <div class="tab-btns-box pull-right">
                    <!--Tabs Header-->
                    <div class="tabs-header">
                        <ul class="product-tab-btns clearfix">
                            <li class="p-tab-btn active-btn" data-tab="#p-tab-1">All</li>
                            <li class="p-tab-btn" data-tab="#p-tab-2">Envoronment</li>
                            <li class="p-tab-btn" data-tab="#p-tab-3">Climate</li>
                            <li class="p-tab-btn" data-tab="#p-tab-4">Plant Trees</li>
                            <li class="p-tab-btn" data-tab="#p-tab-5">Economy</li>
                        </ul>
                    </div>
                </div>
                    
            </div>
            
            <!--Tabs Content-->  
            <div class="p-tabs-content">
                <!--Portfolio Tab / Active Tab-->
                <div class="p-tab active-tab" id="p-tab-1">
                    <div class="three-item-carousel owl-theme owl-carousel">
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <!--Portfolio Tab-->
                <div class="p-tab" id="p-tab-2">
                    <div class="three-item-carousel owl-theme owl-carousel">
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <!--Portfolio Tab-->
                <div class="p-tab" id="p-tab-3">
                    <div class="three-item-carousel owl-theme owl-carousel">
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <!--Portfolio Tab-->
                <div class="p-tab" id="p-tab-4">
                    <div class="three-item-carousel owl-theme owl-carousel">
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                
                <!--Portfolio Tab-->
                <div class="p-tab" id="p-tab-5">
                    <div class="three-item-carousel owl-theme owl-carousel">
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-4.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">grow more plants</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-5.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">Make solar energy</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                        <!--Galery Block-->
                        <div class="gallery-block">
                            <div class="inner-box">
                                <div class="image">
                                    <a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/news-6.jpg" alt="" /></a>
                                </div>
                                <h3><a href="#">watering trees</a></h3>
                                <div class="designation">Ecology, Save earth</div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </div>
        
    </div>
</section>
<!--End Project Section-->