<!--Services Section-->
<section class="services-section-two">
	<div class="auto-container">
    	<!--Sec Title-->
        <div class="sec-title centered">
        	<div class="title">Reasons to Help Us</div>
            <h2>Green Solutions</h2>
        </div>
        <div class="row clearfix">
        	<!--Services Block Six-->
        	<div class="services-block-six col-lg-3 col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                    	<span class="icon flaticon-nature"></span>
                    </div>
                    <h3><a href="services.html">Better Environment</a></h3>
                    <div class="text">Fugiats pariatur excepture caecat acupidata nod proident sint tempor ipsum</div>
                </div>
            </div>
            
            <!--Services Block Six-->
        	<div class="services-block-six col-lg-3 col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                    	<span class="icon flaticon-eco-world"></span>
                    </div>
                    <h3><a href="services.html">Ecology System</a></h3>
                    <div class="text">Fugiats pariatur excepture caecat acupidata nod proident sint tempor ipsum</div>
                </div>
            </div>
            
            <!--Services Block Six-->
        	<div class="services-block-six col-lg-3 col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                    	<span class="icon flaticon-nature-2"></span>
                    </div>
                    <h3><a href="services.html">Saving Trees</a></h3>
                    <div class="text">Fugiats pariatur excepture caecat acupidata nod proident sint tempor ipsum</div>
                </div>
            </div>
            
            <!--Services Block Six-->
        	<div class="services-block-six col-lg-3 col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                    	<span class="icon flaticon-recycle"></span>
                    </div>
                    <h3><a href="services.html">Water Refining</a></h3>
                    <div class="text">Fugiats pariatur excepture caecat acupidata nod proident sint tempor ipsum</div>
                </div>
            </div>
            
        </div>
    </div>
</section>
<!--End Services Section-->