<!--Services Section-->
<section class="services-section">
	<div class="auto-container">
    	<!--Sec Title-->
        <div class="sec-title centered">
        	<div class="title">Reasons to Help Us</div>
            <h2>Working Solutions</h2>
            <div class="text">Aorem ipsum dolor sit amet consectetur adipisicing elit usmod campor incididunt <br> labore temporg dolore magna aliqua ust enim sead minim veniam</div>
        </div>
        <div class="row clearfix">
        
        	<!--Column-->
        	<div class="left-column pull-left col-md-5 col-sm-6 col-xs-12">
            	<!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-1.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">Recycling Waste</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
                <!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-2.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">The Eco System</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
                <!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-3.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">Water Refining</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
            </div>
            
            <!--Column-->
            <div class="right-column pull-right col-md-5 col-sm-6 col-xs-12">
            	
                <!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-4.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">Wind Energy</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
                <!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-5.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">Dynamic Ecology</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
                <!--Services Block-->
                <div class="services-block">
                	<div class="inner-box">
                    	<div class="icon-box">
                        	<span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-6.png" alt="" /></span>
                        </div>
                        <h3><a href="services.html">Saving Plants</a></h3>
                        <div class="text">Dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt inculpa qui officia deserunt mollit anim laboum.</div>
                    </div>
                </div>
                
            </div>
            
            <!--bulb box-->
            <div class="bulb-box">
            	<div class="image-column">
                	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/bulb-icon.png" alt="" />
                </div>
            </div>
            
        </div>
    </div>
</section>
<!--End Services Section-->
