<form class="validate-ajax" action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>" id="<?php echo $this->element->getId(); ?>">

    <?php 
        echo $this->element->identifier;
        echo $this->element->csrf; 

        $option  = $this->element->getDecorator('ViewScript')->getOptions();
        $id_new = $option["id_new"] ;
    ?>

    <input type="hidden" name="id_new" value="<?php echo $id_new ?>">

    <div class="row clearfix">
      <div class="column col-md-6 col-sm-6 col-xs-12">
          <div class="form-group">
              <label for="name"><?php echo $this->translate("Nom") ?></label>
              <?php echo $this->element->name ?>
            </div>
            
            <div class="form-group">
              <label for="email"><?php echo $this->translate("Email") ?></label>
              <?php echo $this->element->email ?>
            </div>
        </div>
        
        
        <div class="column col-md-6 col-sm-6 col-xs-12">
            <div class="form-group">
              <label for="commentaire"><?php echo $this->translate("Commentaire") ?></label>
              <?php echo $this->element->commentaire ?>
            </div>
        </div>
        
    </div>
    <div class="form-group">
      <button type="submit" class="theme-btn btn-style-two ladda-button" data-spinner-color="#fff" data-style="zoom-in" data-size="xs">
          <?php echo strtoupper($this->translate("Ajouter")) ?>
      </button>
    </div>
</form>