<form class="validate-ajax" action="<?php echo $this->escape($this->element->getAction()); ?>" method="<?php echo $this->escape($this->element->getMethod()); ?>" id="<?php echo $this->element->getId(); ?>">

    <?php 
      echo $this->element->identifier;
      echo $this->element->csrf; 

      $notice_url = Application_Class_Url::getMultilingualUrl(array("id_language" => DEFAULT_LANG_ID,"resource" => "pages","action" => "legalnotice")) ;
    ?>

    <div class="row clearfix">
        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
          <label for="name"><?php echo $this->translate("Nom") ?></label>
          <?php echo $this->element->name ?>
        </div>

        <div class="col-md-6 col-sm-6 col-xs-12 form-group">
          <label for="email"><?php echo $this->translate("Adresse email") ?></label>
          <?php echo $this->element->email ?>
        </div>
        
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
          <label for="message"><?php echo $this->translate("Message") ?></label>
          <?php echo $this->element->message ?>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
          <input type="checkbox" name="legal_notice" id="legal_notice" value="1">
          <label for="legal_notice" style="display: contents;cursor: pointer"><?php echo str_replace("#legal_notice#", "<strong><a href='".$notice_url."' target='_blank'>".$this->translate("la politique de confidentialité du site")."</a></strong>", $this->translate("J'ai lu et j'accepte #legal_notice#")) ?>.</label>
          
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
          <div class="g-recaptcha" data-sitekey="<?php echo RECAPTCHA_SITE_KEY ?>"></div>
        </div>

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 form-group">
          <button type="submit" class="theme-btn btn-style-two ladda-button" data-spinner-color="#fff" data-style="zoom-in" data-size="xs">
              <?php echo strtoupper($this->translate("Envoyer")) ?>
          </button>
        </div>
    </div>
</form>