<div class="sidebar-widget popular-posts">
    <div class="sidebar-title"><h2><?php echo $this->translate("Nous suivre") ?></h2></div>

    <div class="fb-page" data-href="https://www.facebook.com/NatoralyAroma" data-tabs="" data-width="" data-height="" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/NatoralyAroma" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/NatoralyAroma">NatoralyAroma</a></blockquote></div>
</div>