<!-- Gallery Widget-->
<div class="sidebar-widget gallery-widget">
    <div class="sidebar-title">
    	<h2>Instagram Feed</h2>
    </div>
    <div class="clearfix">
    	<figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-1.jpg" alt=""></a></figure>
        <figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/2.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-2.jpg" alt=""></a></figure>
        <figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/3.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-3.jpg" alt=""></a></figure>
        <figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-4.jpg" alt=""></a></figure>
        <figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/2.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-5.jpg" alt=""></a></figure>
        <figure class="image"><a href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/3.jpg" class="lightbox-image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/sidebar-gallery-6.jpg" alt=""></a></figure>
    </div>
</div>