<!--Blog Category Widget-->
<div class="sidebar-widget sidebar-blog-category">
    <div class="sidebar-title">
        <h2>Categories</h2>
    </div>
    <ul class="blog-cat">
        <li><a href="#">Water Refining</a></li>
        <li><a href="#">Clean Environment</a></li>
        <li><a href="#">Ecology is Best</a></li>
        <li><a href="#">Solar Energy Conversion</a></li>
        <li><a href="#">Recycling Methods</a></li>
        <li><a href="#">Clean & Clear Water</a></li>
    </ul>
</div>