<!--Call To Action-->
<section class="cal-to-action-section" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/1.jpg);">
  <div class="auto-container">
      <h2>Plant Trees <span><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/logo-icon.png" alt="" /></span> Save <span class="theme_color">green</span></h2>
        <h3>Join Hands with <span class="theme_color">GreenWave</span> to spread the Green</h3>
        <a href="#" class="theme-btn btn-style-three">Join for a cause</a>
    </div>
</section>
<!--End Call To Action-->