<!--Call To Action-->
<section class="cal-to-action-section style-two" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/6.jpg);">
  <div class="auto-container">
      <div class="text-center">
          <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/logo-icon.png" alt="" />
        </div>
        <h3>Do Good & Feel Good with <span class="theme_color">GreenWave</span></h3>
      <h2>become a <span class="theme_color">volunteer</span> today!</h2>
        <a href="#" class="theme-btn btn-style-three">Join us today</a>
    </div>
</section>
<!--End Call To Action-->