<!--Clients Section-->
<section class="clients-section no-padd-bottom">
  <div class="auto-container">
      <!--Sec Title-->
        <div class="sec-title centered">
          <div class="title">Helping Hands</div>
            <h2>Our Supporters</h2>
        </div>
      <!--Sponsors Carousel-->
        <ul class="sponsors-carousel owl-carousel owl-theme">
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/1.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/2.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/3.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/4.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/1.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/2.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/3.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/4.jpg" alt=""></a></figure></li>
        </ul>
    </div>
</section>
<!--End Clients Section-->