<!--Counter Section-->
<section class="counter-section">
  <div class="auto-container">
        <div class="counter-inner">
          <!--Icons Box-->
            <div class="icons-box">
              <span class="icon flaticon-nature-1"></span>
                <span class="icon flaticon-sprout"></span>
                <span class="icon flaticon-plant-1"></span>
            </div>
            <h2>Statistics about the GreenWave</h2>
            
            <!--Fun Facts Section -->
            <div class="fun-facts-section">
                <div class="row clearfix">
                    <!--Column-->
                    <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="inner">
                            <div class="content">
                                <div class="count-outer">
                                    <span class="count-text" data-speed="3000" data-stop="100">0</span>k
                                </div>
                                <div class="counter-title">Funds Collected</div>
                            </div>
                        </div>
                    </div>
                    
                    <!--Column-->
                    <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="inner">
                            <div class="content">
                                <div class="count-outer">
                                    <span class="count-text" data-speed="3000" data-stop="500">0</span>+
                                </div>
                                <div class="counter-title">Completed Events</div>
                            </div>
                        </div>
                    </div>
                    
                    <!--Column-->
                    <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="inner">
                            <div class="content">
                                <div class="count-outer">
                                    <span class="count-text" data-speed="4000" data-stop="1780">0</span>
                                </div>
                                <div class="counter-title">Our Volunteers</div>
                            </div>
                        </div>
                    </div>
                    
                    <!--Column-->
                    <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <div class="inner">
                            <div class="content">
                                <div class="count-outer">
                                    <span class="count-text" data-speed="3000" data-stop="120">0</span>+
                                </div>
                                <div class="counter-title">Awards Won</div>
                            </div>
                        </div>
                    </div>
                        
                </div>
                    
            </div>
            
        </div>
    </div>
</section>
<!--End Counter Section-->