<section class="wprt-section facts">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
            </div><!-- /.col-md-4 -->
            <div class="col-md-8">
                <div class="wprt-spacer" data-desktop="120" data-mobi="80" data-smobi="60"></div>
                <h2 class="text-right text-center-mobile text-white font-family-extend font-size-25 margin-bottom-0 line-height-normal letter-spacing-1px">The Construction Company</h2>
                <h3 class="text-right text-center-mobile text-white font-family-heading font-size-70 line-height-normal margin-bottom-20 letter-spacing-1px"><strong>AWESOME FACTS</strong></h3>
            </div><!-- /.col-md-8 -->
            <div class="col-md-6">
            </div><!-- /.col-md-6 -->
            <div class="col-md-2">
                <div class="wprt-counter text-center white-type has-plus">
                    <div class="number" data-speed="5000" data-to="13691" data-in-viewport="yes">13691</div>
                    <div class="text">PROJECT COMPLETED</div>
                </div>
            </div><!-- /.col-md-2 -->
            <div class="col-md-2">
                <div class="wprt-counter text-center white-type has-plus">
                    <div class="number" data-speed="5000" data-to="1725" data-in-viewport="yes">1725</div>
                    <div class="text">SATISFIED CLIENTS</div>
                </div>
            </div><!-- /.col-md-2 -->
            <div class="col-md-2">
                <div class="wprt-counter text-center white-type has-plus">
                    <div class="number" data-speed="5000" data-to="984" data-in-viewport="yes">984</div>
                    <div class="text">WORKERS EMPLOYED</div>
                </div>
            </div><!-- /.col-md-2 -->
            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="130" data-mobi="80" data-smobi="60"></div>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>