<!--Gallery Section-->
<section class="gallery-section">
  <div class="auto-container">
      <!--Sec Title-->
        <div class="sec-title clearfix">
          <div class="pull-left">
            <div class="title">Reasons to Help Us</div>
              <h2>Projects Gallery</h2>
            </div>
            <div class="pull-right">
              <!--Filter-->
                <div class="filters clearfix">
                    <ul class="filter-tabs filter-btns">
                        <li class="filter active" data-role="button" data-filter="all">All</li>
                        <li class="filter" data-role="button" data-filter=".environment">environment</li>
                        <li class="filter" data-role="button" data-filter=".climate">Climate</li>
                        <li class="filter" data-role="button" data-filter=".plant">Plant Trees</li>
                        <li class="filter" data-role="button" data-filter=".economy">Economy</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <div class="filter-list clearfix">
            
        <!--Gallery Block-->
        <div class="gallery-item mix all plant economy col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all economy climate col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/3.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/3.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all environment col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/8.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/8.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all plant economy col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/9.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/9.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all economy climate environment col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/10.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/10.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all plant climate economy col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/11.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/11.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all economy environment col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/12.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/12.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!--Gallery Block-->
        <div class="gallery-item mix all plant climate col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="inner-box">
                <div class="image">
                    <img src="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" alt="" />
                    <div class="overlay-box">
                        <div class="content">
                            <a href="#"><span class="icon fa fa-link"></span></a>
                            <a class="lightbox-image" href="<?php echo THEMES_DEFAULT_URL ?>images/gallery/1.jpg" title="Image Title Here" data-fancybox-group="gallery"><span class="icon fa fa-search"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
</section>
<!--End Gallery Section-->