<!-- Hero Background SlideShow -->
<div id="typed-strings">
    <p>FOCUS ON YOU</p>
    <p>HAVE EXPERIENCE</p>
</div>

<div id="hero-section" data-number="3" data-image-1="<?php echo THEMES_DEFAULT_URL ?>img/slider/1.jpg" data-image-2="<?php echo THEMES_DEFAULT_URL ?>img/slider/2.jpg" data-image-3="<?php echo THEMES_DEFAULT_URL ?>img/slider/6.jpg" data-effect="fade">
    <div class="hero-content">
        <div class="hero-title typing" data-min="22px" data-max="80px">
            <h1>WE <span id="typed"></span></h1>
        </div>

        <div class="hero-text">
            <p>Our experience ensures that your projects will be done right and with the upmost professionalism.</p>
        </div>

        <div class="hero-button">
            <a class="wprt-button rounded-3px" href="#">LEARN MORE</a>
        </div>
    </div><!-- /.hero-content -->

    <a class="arrow scroll-target" href="#services-section"></a><!-- change href value to ID of section you want to scroll down -->
</div>