<?php  
    $option = Zend_Registry::get("option") ;

    $sliders = array() ;

    $getIdCategoryGroupByModule = Application_Model_Module::getIdCategoryGroupByModule(2) ;
    $categories = Application_Model_Category::getCategoryByIdCategoryGroup($getIdCategoryGroupByModule,1) ;

    if ($option->slider == "text" || empty($categories)) {
        $get = Application_Model_Page::getPageByCatId(10) ;
        $sliders = $get["content"] ;
    }
    else{
        foreach ($categories as $k => $category) {
            $t = Application_Model_Category::getCategoryById($category["id"]) ;
            $sliders[$k]["title"] = $t["short_description_".DEFAULT_LANG_ABBR] ;
            $sliders[$k]["text"] = $t["text_".DEFAULT_LANG_ABBR] ;
            $sliders[$k]["seo_permalink"] = $t["seo_permalink_".DEFAULT_LANG_ABBR] ;
            $sliders[$k]["cover"]["url"] = $t["cover"]["url"] ;
        }
    }
?>

<!--Main Slider-->
<section class="main-slider">
  
    <div class="rev_slider_wrapper fullwidthbanner-container"  id="rev_slider_one_wrapper" data-source="gallery">
        <div class="rev_slider fullwidthabanner" id="rev_slider_one" data-version="5.4.1">
            <ul>

                <?php if (empty($sliders)){ ?>
                    <li data-description="Slide Description" data-easein="default" data-easeout="default" data-fsmasterspeed="1500" data-fsslotamount="7" data-fstransition="fade" data-hideafterloop="0" data-hideslideonmobile="off" data-index="rs-1687" data-masterspeed="default" data-param1="" data-param10="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-rotate="0" data-saveperformance="off" data-slotamount="default" data-thumb="<?php echo THEMES_DEFAULT_URL ?>images/main-slider/slider2.jpg" data-title="Slide Title" data-transition="parallaxvertical">
                    <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="<?php echo THEMES_DEFAULT_URL ?>images/main-slider/slider2.jpg"> 
                    
                    <div class="tp-caption" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[0,0,0,0]"
                    data-paddingright="[0,0,0,0]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-width="['1100','1024','600','290']"
                    data-whitespace="normal"
                    data-hoffset="['15','15','15','15']"
                    data-voffset="['-130','-120','-120','-125']"
                    data-x="['center','center','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                    style="z-index: 7; white-space: nowrap;text-transform:left;">
                      <div class="title"><?php echo Zend_Registry::get("option")->site_name ?></div>
                    </div>
                    
                    <div class="tp-caption" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[0,0,0,0]"
                    data-paddingright="[0,0,0,0]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-width="['1100','1024','600','400']"
                    data-whitespace="normal"
                    data-hoffset="['15','15','15','15']"
                    data-voffset="['-45','-35','-45','-60']"
                    data-x="['center','center','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                    style="z-index: 7; white-space: nowrap;text-transform:left;">
                      <h2><?php echo $this->translate("Huilles essentielles de Madagascar") ?></h2>
                    </div>
                    
                    <div class="tp-caption" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[0,0,0,0]"
                    data-paddingright="[0,0,0,0]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-width="['1100','950','700','450']"
                    data-whitespace="normal"
                    data-hoffset="['15','15','15','15']"
                    data-voffset="['30','45','30','30']"
                    data-x="['center','center','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                    style="z-index: 7; white-space: nowrap;text-transform:left;">
                      <div class="text text-center text-white"><?php echo $this->translate("Nous sommes producteur et distillateur de matières premières aromatiques, et huiles essentielles d’origine Madagascar, biologiques et conventionnelles.") ?></div>
                    </div>
                    
                    <div class="tp-caption tp-resizeme" 
                    data-paddingbottom="[0,0,0,0]"
                    data-paddingleft="[0,0,0,0]"
                    data-paddingright="[0,0,0,0]"
                    data-paddingtop="[0,0,0,0]"
                    data-responsive_offset="on"
                    data-type="text"
                    data-height="none"
                    data-width="['900','600','600','420']"
                    data-whitespace="normal"
                    data-hoffset="['15','15','15','15']"
                    data-voffset="['120','130','115','120']"
                    data-x="['center','center','center','center']"
                    data-y="['middle','middle','middle','middle']"
                    data-textalign="['top','top','top','top']"
                    data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                    style="z-index: 7; white-space: nowrap;text-transform:left;">
                    </div>
                    
                    </li>
                <?php }else{ ?>
                    <?php foreach ($sliders as $key => $slider): ?>
                         <li data-description="<?php echo $slider["title"] ?>" data-easein="default" data-easeout="default" data-fsmasterspeed="1500" data-fsslotamount="7" data-fstransition="fade" data-hideafterloop="0" data-hideslideonmobile="off" data-index="rs-<?php echo $key?>" data-masterspeed="default" data-param1="" data-param10="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-rotate="0" data-saveperformance="off" data-slotamount="default" data-thumb="<?php echo $slider["cover"]["url"] ?>" data-title="<?php echo $slider["title"] ?>" data-transition="parallaxvertical">
                         <img alt="<?php echo $slider["title"] ?>" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="<?php echo $slider["cover"]["url"] ?>"> 
                         
                         <div class="tp-caption" 
                         data-paddingbottom="[0,0,0,0]"
                         data-paddingleft="[0,0,0,0]"
                         data-paddingright="[0,0,0,0]"
                         data-paddingtop="[0,0,0,0]"
                         data-responsive_offset="on"
                         data-type="text"
                         data-height="none"
                         data-width="['1100','1024','600','290']"
                         data-whitespace="normal"
                         data-hoffset="['15','15','15','15']"
                         data-voffset="['-250','-120','-120','-125']"
                         data-x="['center','center','center','center']"
                         data-y="['middle','middle','middle','middle']"
                         data-textalign="['top','top','top','top']"
                         data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                         style="z-index: 7; white-space: nowrap;text-transform:left;">
                           <div class="title"><?php echo Zend_Registry::get("option")->site_name ?></div>
                         </div>
                         
                         <div class="tp-caption" 
                         data-paddingbottom="[0,0,0,0]"
                         data-paddingleft="[0,0,0,0]"
                         data-paddingright="[0,0,0,0]"
                         data-paddingtop="[50,50,50,50]"
                         data-responsive_offset="on"
                         data-type="text"
                         data-height="none"
                         data-width="['1100','1024','600','400']"
                         data-whitespace="normal"
                         data-hoffset="['15','15','15','15']"
                         data-voffset="['-165','-35','-45','-60']"
                         data-x="['center','center','center','center']"
                         data-y="['middle','middle','middle','middle']"
                         data-textalign="['top','top','top','top']"
                         data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                         style="z-index: 7; white-space: nowrap;text-transform:left;">
                           <h2><?php echo $slider["title"] ?></h2>
                         </div>
                         
                         <div class="tp-caption" 
                         data-paddingbottom="[0,0,0,0]"
                         data-paddingleft="[0,0,0,0]"
                         data-paddingright="[0,0,0,0]"
                         data-paddingtop="[175,175,175,175]"
                         data-responsive_offset="on"
                         data-type="text"
                         data-height="none"
                         data-width="['1100','950','700','450']"
                         data-whitespace="normal"
                         data-hoffset="['15','15','15','15']"
                         data-voffset="['-90','45','30','30']"
                         data-x="['center','center','center','center']"
                         data-y="['middle','middle','middle','middle']"
                         data-textalign="['top','top','top','top']"
                         data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                         style="z-index: 7; white-space: nowrap;text-transform:left;">
                           <div class="text text-center text-white"><?php echo $slider["text"] ?></div>
                         </div>
                        
                            <?php if ($option->slider == "products"): 
                                $url = Application_Class_Url::getMultilingualUrl(array("id_language" => DEFAULT_LANG_ID,"resource" => "products","action" => "fiche")) ;
                                $url = str_replace("#category_permalink#", $t["category_permalink"], $url) ;
                                $url = str_replace("#permalink#", $slider["seo_permalink"], $url) ;
                            ?>

                                 <div class="tp-caption tp-resizeme hidden-sm hidden-xs" 
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[175,175,175,175]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['900','600','600','420']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['0','130','115','120']"
                                 data-x="['center','center','center','center']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'
                                 style="z-index: 7; white-space: nowrap;text-transform:left;">
                                        <div class="text-center">
                                            <a href="<?php echo $url ?>" class="theme-btn btn-style-two"><?php echo $this->translate("Lire la suite") ?></a> 
                                        </div>
                                     
                                 </div>
                            <?php endif ?>
                         </li>
                    <?php endforeach ?>
                <?php } ?>
                
            </ul>
        </div>
    </div>
</section>
<!--End Main Slider-->