<section class="wprt-section promotion" id="promotion-section">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="wprt-spacer" data-desktop="8" data-mobi="8" data-smobi="8"></div>
                <h2 class="text-white text-center-mobile font-size-20 margin-bottom-0">Contractors & Construction Managers Since 1981</h2>
                <div class="wprt-spacer" data-desktop="0" data-mobi="20" data-smobi="20"></div>
            </div><!-- /.col-md-8 -->

            <div class="col-md-4">
                <div class="text-right text-center-mobile"><a href="#" class="wprt-button white rounded-3px">GET A QUOTE</a></div>
                <div class="wprt-spacer" data-desktop="0" data-mobi="15" data-smobi="15"></div>
            </div><!-- /.col-md-4 -->

        </div><!-- /.row -->
    </div><!-- /.container -->
</section>