<!-- Slider -->
<div class="rev_slider_wrapper fullwidthbanner-container">
    <div id="rev-slider1" class="rev_slider fullwidthabanner">
        <ul>
            <!-- Slide -->
            <li data-transition="fade" data-slotamount="default" data-easein="Power3.easeInOut" data-easeout="Power3.easeInOut" data-masterspeed="1500" data-thumb="<?php echo THEMES_DEFAULT_URL?>/img/slider/1.jpg" data-rotate="0" data-saveperformance="off" data-title="BEST COMPANY">
                <!-- Main Image -->
                <img src="<?php echo THEMES_DEFAULT_URL?>/img/slider/1.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-no-retina>
                <!-- Layers -->
                <div class="tp-caption tp-resizeme text-white font-family-extend letter-spacing-7px"
                    data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['-50','-50','-50','-50']"
                    data-fontsize="['28','24','20','18']"
                    data-lineheight="['40','36','28','26']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;"
                    data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;"
                    data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                    data-mask_out="x:0;y:0;s:inherit;e:inherit;"
                    data-start="1000"
                    data-splitin="none"
                    data-splitout="none"
                    data-responsive_offset="on"
                    data-lasttriggerstate="reset">
                    Welcome to Construction
                </div>
                <div class="tp-caption tp-resizeme text-white font-family-heading letter-spacing-1px font-weight-700"
                    data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['26','20','16','10']"
                    data-fontsize="['70','60','50','40']"
                    data-lineheight="['80','70','60','50']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;"
                    data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;"
                    data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                    data-mask_out="x:0;y:0;s:inherit;e:inherit;"
                    data-start="1000"
                    data-splitin="none"
                    data-splitout="none"
                    data-responsive_offset="on">
                    THE <span class="text-accent-color">BEST</span> COMPANY
                </div>
                <div class="tp-caption"
                    data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['156','136','116','106']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:300;e:Power1.easeInOut;"
                    data-style_hover="c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);cursor:pointer;"
                    data-transform_in="y:50px;opacity:0;s:1500;e:Power4.easeInOut;"
                    data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                    data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
                    data-start="1250"
                    data-splitin="none"
                    data-splitout="none"
                    data-actions='[{"event":"click","action":"scrollbelow","offset":"20px"}]'
                    data-responsive="on">
                    <a class="wprt-button big rounded-3px">OUR PORTFOLIO</a>
                </div>
            </li>
            <!-- End Slide -->

            <!-- Slide -->
            <li data-transition="boxfade" data-slotamount="7" data-easein="Expo.easeOut" data-easeout="Expo.easeOut" data-masterspeed="2000" data-thumb="<?php echo THEMES_DEFAULT_URL?>/img/slider/2.jpg" data-rotate="0" data-saveperformance="off" data-title="SINCE 1981">
                <!-- Main Image -->
                <img src="<?php echo THEMES_DEFAULT_URL?>/img/slider/2.jpg" alt="" data-bgposition="center center" data-no-retina>
                <!-- Layers -->
                <div class="tp-caption tp-resizeme text-white font-family-heading letter-spacing-1px font-weight-700"
                    data-x="['left','left','left','left']" data-hoffset="['50','30','30','30']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['-75','-70','-70','-50']"
                    data-fontsize="['58','58','58','35']"
                    data-lineheight="['66','65','56','42']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_in="z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;"
                    data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                    data-mask_in="x:0px;y:0px;"
                    data-mask_out="x:inherit;y:inherit;"
                    data-start="1500"
                    data-splitin="none"
                    data-splitout="none"
                    data-responsive_offset="on">
                    CONSTRUCTION
                </div>
                <div class="tp-caption tp-resizeme text-white font-family-heading letter-spacing-1px font-weight-700"
                    data-x="['left','left','left','left']" data-hoffset="['50','30','30','30']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']"
                    data-fontsize="['58','58','58','35']"
                    data-lineheight="['66','65','56','42']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_in="z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:1500;e:Power3.easeInOut;"
                    data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                    data-mask_in="x:0px;y:0px;"
                    data-mask_out="x:inherit;y:inherit;"
                    data-start="1500"
                    data-splitin="none"
                    data-splitout="none"
                    data-responsive_offset="on">
                    MANAGERS <span class="text-accent-color">SINCE 1981</span>
                </div>
                <div class="tp-caption tp-resizeme text-white font-family-extend letter-spacing-4px"
                    data-x="['left','left','left','left']" data-hoffset="['55','30','30','30']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['68','100','100','40']"
                    data-fontsize="['28','26','24','15']"
                    data-lineheight="['40','40','40','28']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;"
                    data-transform_out="auto:auto;s:1000;e:Power3.easeInOut;"
                    data-mask_in="x:0px;y:0px;s:inherit;e:inherit;"
                    data-mask_out="x:0;y:0;s:inherit;e:inherit;"
                    data-start="1000"
                    data-splitin="none"
                    data-splitout="none"
                    data-responsive_offset="on"
                    data-lasttriggerstate="reset">
                    Fast and Reliable Service for Your Project
                </div>
                <div class="tp-caption"
                    data-x="['left','left','left','left']" data-hoffset="['55','30','30','30']"
                    data-y="['middle','middle','middle','middle']" data-voffset="['160','150','140','125']"
                    data-width="none"
                    data-height="none"
                    data-whitespace="nowrap"
                    data-transform_idle="o:1;"
                    data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:300;e:Power1.easeInOut;"
                    data-style_hover="c:rgba(255, 255, 255, 1.00);bc:rgba(255, 255, 255, 1.00);cursor:pointer;"
                    data-transform_in="y:50px;opacity:0;s:1000;e:Power4.easeInOut;"
                    data-transform_out="y:[175%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;"
                    data-mask_out="x:inherit;y:inherit;s:inherit;e:inherit;"
                    data-start="1250"
                    data-splitin="none"
                    data-splitout="none"
                    data-actions='[{"event":"click","action":"scrollbelow","offset":"20px"}]'
                    data-responsive="on">
                    <a class="wprt-button big rounded-3px">CONTACT US</a>
                </div>
            </li>
            <!-- End Slide -->
        </ul>
        <div class="tp-bannertimer tp-bottom"></div>
    </div>
</div>