<section class="wprt-section services" id="services-section">
   <div class="container">
       <div class="row">
           <div class="col-md-12">
               <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
               <h2 class="text-center margin-bottom-10">MAIN SERVICES</h2>
               <div class="wprt-lines style-2 custom-1">
                   <div class="line-1"></div>
               </div>
               <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>
           </div><!-- /.col-md-12 -->
                   
           <div class="col-md-4">
               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-drawing"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">Construction Consultant</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>

               <div class="wprt-spacer" data-desktop="50" data-mobi="30" data-smobi="30"></div>

               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-engineer"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">General Contracting</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>

               <div class="wprt-spacer" data-desktop="0" data-mobi="30" data-smobi="30"></div>
           </div><!-- /.col-md-4 -->

           <div class="col-md-4">
               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-drawing-compass"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">Architectural Design</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>

               <div class="wprt-spacer" data-desktop="50" data-mobi="30" data-smobi="30"></div>

               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-drill-2"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">Resconstruction Services</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>

               <div class="wprt-spacer" data-desktop="0" data-mobi="30" data-smobi="30"></div>
           </div><!-- /.col-md-4 -->

           <div class="col-md-4">
               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-light-bulb"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">Electrical System</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>

               <div class="wprt-spacer" data-desktop="50" data-mobi="30" data-smobi="30"></div>

               <div class="wprt-icon-box accent-background rounded icon-effect-2 icon-left">
                   <div class="icon-wrap">
                       <span class="dd-icon icon-pipe-11"></span>
                   </div>
                   <div class="content-wrap">
                       <h3 class="dd-title font-size-18"><a href="#">Plumbilg Services</a></h3>
                       <p>Vestibulum eu libero volutpat, portas quam, tempus sem. Donec sodales quam id lorem lobortis, vitae interdum nisl.</p>
                   </div>
               </div>
           </div><!-- /.col-md-4 -->

           <div class="col-md-12">
               <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
           </div><!-- /.col-md-12 -->
       </div><!-- /.row -->
   </div><!-- /.container -->
</section>