<section class="wprt-section testiminials">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
            </div><!-- /.col-md-12 -->

            <div class="col-md-6">
                <h2>OUR PARTNERS</h2>
                <div class="wprt-lines style-1 custom-3">
                    <div class="line-1"></div>
                    <div class="line-2"></div>
                </div>
                <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>

                <div class="wprt-partner-grid has-outline col-3 gutter-10">
                    <div class="partner-wrap clearfix">
                        <div class="partner-row clearfix">
                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/1.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->

                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/2.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->

                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/3.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->
                        </div>

                        <div class="partner-row clearfix">
                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/4.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->

                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/5.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->

                            <div class="partner-item">
                                <div class="inner-item">
                                    <a target="_blank" href="#"><img src="<?php echo THEMES_DEFAULT_URL?>/img/partners/6.png" alt="image" /></a>
                                </div>
                            </div><!-- /.partner-item -->
                        </div>
                    </div><!-- /.partner-wrap -->
                </div><!-- /.wprt-partner-grid -->

                <div class="wprt-spacer" data-desktop="0" data-mobi="40" data-smobi="40"></div>
            </div><!-- /.col-md-6 -->

            <div class="col-md-6">
                <h2>TESTIMONIALS</h2>
                <div class="wprt-lines style-1 custom-3">
                    <div class="line-1"></div>
                    <div class="line-2"></div>
                </div>
                <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>

                <div class="wprt-testimonials has-outline arrow-style-2 has-arrows arrow60 arrow-light" data-layout="slider" data-column="1" data-column2="1" data-column3="1" data-column4="1" data-gaph="0" data-gapv="0">
                    <div id="testimonials-wrap" class="cbp">
                        <div class="cbp-item">
                            <div class="customer clearfix">
                                <div class="inner">
                                    <div class="image"><img src="<?php echo THEMES_DEFAULT_URL?>/img/testimonials/1.jpg" alt="image" /></div>
                                    <h4 class="name">DON PAULSON</h4>
                                    <div class="position">Architectural Co.</div>
                                    <blockquote class="whisper">Your efficient planning, scheduling, management, and supervision resulted in timely completion and a quality facility...Particularly refreshing was the spirit of cooperation demonstrated by your firm which served to minimize costly delays and contract modifications.</blockquote>
                                </div>
                            </div>
                        </div><!-- /.cbp-item -->

                        <div class="cbp-item">
                            <div class="customer clearfix">
                                <div class="inner">
                                    <div class="image"><img src="<?php echo THEMES_DEFAULT_URL?>/img/testimonials/2.jpg" alt="image" /></div>
                                    <h4 class="name">DON PAULSON</h4>
                                    <div class="position">Architectural Co.</div>
                                    <blockquote class="whisper">Your efficient planning, scheduling, management, and supervision resulted in timely completion and a quality facility...Particularly refreshing was the spirit of cooperation demonstrated by your firm which served to minimize costly delays and contract modifications.</blockquote>
                                </div>
                            </div>
                        </div><!-- /.cbp-item -->

                        <div class="cbp-item">
                            <div class="customer clearfix">
                                <div class="inner">
                                    <div class="image"><img src="<?php echo THEMES_DEFAULT_URL?>/img/testimonials/3.jpg" alt="image" /></div>
                                    <h4 class="name">DON PAULSON</h4>
                                    <div class="position">Architectural Co.</div>
                                    <blockquote class="whisper">Your efficient planning, scheduling, management, and supervision resulted in timely completion and a quality facility...Particularly refreshing was the spirit of cooperation demonstrated by your firm which served to minimize costly delays and contract modifications.</blockquote>
                                </div>
                            </div>
                        </div><!-- /.cbp-item -->
                    </div><!-- /#service-wrap -->
                </div><!-- /.wprt-service -->
            </div><!-- /.col-md-6 -->

            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>