<!--Testimonial Section-->
<section class="testimonial-section">
  <div class="auto-container">
      <div class="row clearfix">
          
            <!--Column-->
            <div class="title-column col-md-4 col-sm-12 col-xs-12">
              <div class="quote"><span class="icon flaticon-double-quotes"></span></div>
                <div class="sec-title">
                  <div class="title">What People Saying</div>
                    <h2>The Testimonials</h2>
                </div>
            </div>
            <!--Column-->
            <div class="column col-md-8 col-sm-12 col-xs-12">
              <div class="single-item-carousel owl-theme owl-carousel">
                
                  <!--Testimonial Block-->
                  <div class="testimonial-block">
                      <div class="inner-box">
                          <div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                  <div class="testimonial-block">
                      <div class="inner-box">
                          <div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                  <div class="testimonial-block">
                      <div class="inner-box">
                          <div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                  <div class="testimonial-block">
                      <div class="inner-box">
                          <div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>
<!--End Testimonial Section-->
