<!--Volunter Section-->
<section class="volunter-section">
  <div class="auto-container">
      <!--Sec Title-->
        <div class="sec-title centered">
          <div class="title">Reasons to Join Us</div>
          <h2>The Volunteers</h2>
        </div>
        <div class="row clearfix">
          
            <!--Volunter Member-->
            <div class="volunter-member col-md-6 col-sm-12 col-xs-12">
              <div class="inner-box">
                  <div class="row clearfix">
                      <!--Image Column-->
                      <div class="image-column col-md-5 col-sm-5 col-xs-12">
                          <div class="image">
                              <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-1.jpg" alt="" />
                                <div class="overlay-box">
                                  <ul class="social-icon-one">
                                      <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                      <div class="content-column col-md-7 col-sm-7 col-xs-12">
                          <div class="inner-column">
                              <h3>William Hales</h3>
                                <div class="designation">Founder</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member col-md-6 col-sm-12 col-xs-12">
              <div class="inner-box">
                  <div class="row clearfix">
                      <!--Image Column-->
                      <div class="image-column col-md-5 col-sm-5 col-xs-12">
                          <div class="image">
                              <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-2.jpg" alt="" />
                                <div class="overlay-box">
                                  <ul class="social-icon-one">
                                      <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                      <div class="content-column col-md-7 col-sm-7 col-xs-12">
                          <div class="inner-column">
                              <h3>Arthur John</h3>
                                <div class="designation">Senior Admin</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member col-md-6 col-sm-12 col-xs-12">
              <div class="inner-box">
                  <div class="row clearfix">
                      <!--Image Column-->
                      <div class="image-column col-md-5 col-sm-5 col-xs-12">
                          <div class="image">
                              <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-3.jpg" alt="" />
                                <div class="overlay-box">
                                  <ul class="social-icon-one">
                                      <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                      <div class="content-column col-md-7 col-sm-7 col-xs-12">
                          <div class="inner-column">
                              <h3>Matilda Rose</h3>
                                <div class="designation">Volunteer</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member col-md-6 col-sm-12 col-xs-12">
              <div class="inner-box">
                  <div class="row clearfix">
                      <!--Image Column-->
                      <div class="image-column col-md-5 col-sm-5 col-xs-12">
                          <div class="image">
                              <img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-4.jpg" alt="" />
                                <div class="overlay-box">
                                  <ul class="social-icon-one">
                                      <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                      <div class="content-column col-md-7 col-sm-7 col-xs-12">
                          <div class="inner-column">
                              <h3>Robyn Kate</h3>
                                <div class="designation">Volunteer</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
        </div>
        <br><br>
        <div class="text-center">
          <a href="#" class="theme-btn btn-style-two">more volunteers</a>
        </div>
        
    </div>
</section>
<!--End Volunter Section-->