<section class="wprt-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
                <h2>WHY CHOOSE US?</h2>
                <div class="wprt-lines style-1 custom-3">
                    <div class="line-1"></div>
                    <div class="line-2"></div>
                </div>
                <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>

                <div class="wprt-toggle style-1">
                    <h3 class="toggle-title">We have 30 plus years in the building industry</h3>
                    <div class="toggle-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a metus pellentesque, scelerisque ex sed, volutpat nisi. Curabitur tortor mi, eleifend ornare lobortis non. Nulla porta purus quis iaculis ultrices. Proin aliquam sem at nibh hendrerit sagittis. Nullam ornare odio eu lacus tincidunt malesuada. Sed eu vestibulum elit. Curabitur tortor mi, eleifend ornare.</div>
                </div>

                <div class="wprt-toggle active style-1">
                    <h3 class="toggle-title">Quality construction continues after the project</h3>
                    <div class="toggle-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a metus pellentesque, scelerisque ex sed, volutpat nisi. Curabitur tortor mi, eleifend ornare lobortis non. Nulla porta purus quis iaculis ultrices. Proin aliquam sem at nibh hendrerit sagittis. Nullam ornare odio eu lacus tincidunt malesuada. Sed eu vestibulum elit. Curabitur tortor mi, eleifend ornare.</div>
                </div>

                <div class="wprt-toggle style-1">
                    <h3 class="toggle-title">We use technology to do the job more quickly</h3>
                    <div class="toggle-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a metus pellentesque, scelerisque ex sed, volutpat nisi. Curabitur tortor mi, eleifend ornare lobortis non. Nulla porta purus quis iaculis ultrices. Proin aliquam sem at nibh hendrerit sagittis. Nullam ornare odio eu lacus tincidunt malesuada. Sed eu vestibulum elit. Curabitur tortor mi, eleifend ornare.</div>
                </div>

                <div class="wprt-toggle style-1">
                    <h3 class="toggle-title">Employees are continually trained on safety issues</h3>
                    <div class="toggle-content">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a metus pellentesque, scelerisque ex sed, volutpat nisi. Curabitur tortor mi, eleifend ornare lobortis non. Nulla porta purus quis iaculis ultrices. Proin aliquam sem at nibh hendrerit sagittis. Nullam ornare odio eu lacus tincidunt malesuada. Sed eu vestibulum elit. Curabitur tortor mi, eleifend ornare.</div>
                </div>
            </div><!-- /.col-md-6 -->

            <div class="col-md-6">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
                <h2>ABOUT US</h2>
                <div class="wprt-lines style-1 custom-3">
                    <div class="line-1"></div>
                    <div class="line-2"></div>
                </div>
                <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>

                <div class="wprt-galleries galleries w-570px" data-width="135" data-margin="10">
                    <div id="wprt-slider" class="flexslider">
                        <ul class="slides">
                            <li class="flex-active-slide">
                                <a class="zoom" href="<?php echo THEMES_DEFAULT_URL?>/img/gallery/1.jpg"><i class="fa fa-arrows-alt"></i></a>
                                <img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/1.jpg" alt="image" />
                            </li>

                            <li class="flex-active-slide">
                                <a class="zoom" href="<?php echo THEMES_DEFAULT_URL?>/img/gallery/2.jpg"><i class="fa fa-arrows-alt"></i></a>
                                <img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/2.jpg" alt="image" />
                            </li>

                            <li class="flex-active-slide">
                                <a class="zoom" href="<?php echo THEMES_DEFAULT_URL?>/img/gallery/3.jpg"><i class="fa fa-arrows-alt"></i></a>
                                <img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/3.jpg" alt="image" />
                            </li>

                            <li class="flex-active-slide">
                                <a class="zoom" href="<?php echo THEMES_DEFAULT_URL?>/img/gallery/4.jpg"><i class="fa fa-arrows-alt"></i></a>
                                <img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/4.jpg" alt="image" />
                            </li>
                        </ul>
                    </div>

                    <div id="wprt-carousel" class="flexslider">
                        <ul class="slides">
                            <li><img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/1-s.jpg" alt="image"></li>
                            <li><img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/2-s.jpg" alt="image"></li>
                            <li><img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/3-s.jpg" alt="image"></li>
                            <li><img src="<?php echo THEMES_DEFAULT_URL?>/img/gallery/4-s.jpg" alt="image"></li>
                        </ul>
                    </div>
                </div>
            </div><!-- /.col-md-6 -->

            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>
