<section class="wprt-section works parallax">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="70" data-mobi="60" data-smobi="60"></div>
                <h2 class="text-left text-white">FEATURED WORK</h2>
                <div class="wprt-lines custom-2">
                    <div class="line-1"></div>
                </div>
                <div class="wprt-spacer" data-desktop="50" data-mobi="40" data-smobi="40"></div>
            </div><!-- /.col-md-12 -->
                    
            <div class="col-md-12">
                <div class="wprt-project arrow-style-2 has-arrows arrow60 arrow-dark" data-layout="slider" data-column="3" data-column2="3" data-column3="2" data-column4="1" data-gaph="30" data-gapv="30">
                    <div id="projects" class="cbp">
                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <div class="grid">
                                    <figure class="effect-sadie">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/1.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>
                                    </div>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/1-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-honey">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/2.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-2.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/2-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-sadie">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/3.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-3.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/3-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-zoe">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/4.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-4.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/4-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-oscar">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/5.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/5-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-sadie">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/6.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-2.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/6-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-sadie">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/7.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-2.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/7-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->

                        <div class="cbp-item">
                            <div class="project-item">
                                <div class="inner">
                                    <figure class="effect-sadie">
                                        <img src="<?php echo THEMES_DEFAULT_URL?>/img/projects/8.jpg" alt="image" />
                                        <figcaption>
                                            <div>
                                                <h2><a target="_blank" href="page-project-detail-2.html">LUXURY BUILDINGS</a></h2>
                                                <p>Construction</p>
                                            </div>
                                        </figcaption>           
                                    </figure>

                                    <a class="project-zoom cbp-lightbox" href="<?php echo THEMES_DEFAULT_URL?>/img/projects/8-full.jpg" data-title="LUXURY BUILDINGS">
                                        <i class="fa fa-arrows-alt"></i>
                                    </a>
                                </div>
                            </div>
                        </div><!--/.cbp-item -->
                    </div><!-- /#projects -->
                </div><!--/.wprt-project -->
            </div><!-- /.col-md-12 -->

            <div class="col-md-12">
                <div class="wprt-spacer" data-desktop="80" data-mobi="60" data-smobi="60"></div>
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section>
