<!--Content Side-->
<?php 
    $q =  Zend_Controller_Front::getInstance()->getRequest()->getParam('q');
?>

<div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">

    <?php if (!empty($this->paginator)): ?>
        <?php foreach ($this->paginator as $new): 
            $tab_params["id_language"] = DEFAULT_LANG_ID ;
            $tab_params["resource"] = "news" ;
            $tab_params["action"] = "fiche" ;

            $getUrl = Application_Class_Url::getMultilingualUrl($tab_params) ;
        ?>
                <!--News Style Two-->
                <div class="news-style-two">
                    <div class="inner-box">
                        <div class="lower-content">
                            <h3><a href="<?php echo str_replace("#permalink#", $new["seo_permalink"], $getUrl) ?>"><?php echo $new["title"] ?></a></h3>
                            <div class="text">
                                <?php echo Application_Class_Utils::chopText($new['text'],250) ?>&nbsp;&nbsp;<a href="<?php echo str_replace("#permalink#", $new["seo_permalink"], $getUrl) ?>" class="" style="text-decoration: underline;"><?php echo $this->translate("Lire la suite") ?></a>
                            </div>

                            <div class="image">
                                <a href="<?php echo str_replace("#permalink#", $new["seo_permalink"], $getUrl) ?>">
                                    <?php /* ?><img src="<?php echo $new["cover"]["url"] ?>" alt="" /><?php */ ?>
                                    <div style="background: url(<?php echo $new["cover"]["url"] ?>);background-size: cover;min-height:500px;max-height:500px;width: 100%"></div>
                                </a>
                            </div>

                            <div class="upper-box clearfix">
                                <div class="pull-left">
                                    <div class="post-date pt-10"><?php echo str_replace("#date_publication#", "<span>".Application_Class_Date::formatfromMysql($new["create_date"])."</span>", $this->translate("Publié le : #date_publication# ")) ?></div>
                                </div>

                                <?php echo $this->partial("news/_partials/post-meta.phtml",array("id_new" => $new["page_id"])) ?>

                            </div>
                        </div>
                    </div>
                </div>
        <?php endforeach ?>
    <?php endif ?>

    <?php
        echo "<input type='hidden' name='__pagination__' data-resource_type='news' data-search='".$q."'>" ; 
        echo $this->paginator;
    ?>
</div>