<style type="text/css">
    .services-block-five .inner-box h3{font-size: 18px !important}
</style>

<?php 
    $section_1 = $this->section_1 ;
    $content = $section_1["content"] ;
?>

<section class="services-section-two style-two">
    <div class="auto-container">
    	<!--Sec Title-->
        <div class="sec-title centered aos-init aos-animate" data-aos="fade-up" data-aos-duration="700">
            <h2><?php echo $section_1["category_title"] ?></h2>
            <div class="text"><?php echo $section_1["category_description"]; ?></div>
        </div>
        <div class="row clearfix">

            <?php if (!empty($content)): ?>
                <?php foreach ($content as $content): ?>
                    <!--Services Block Five-->
                    <div class="services-block-five col-md-4 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $content["cover"]["url"] ?>" alt="<?php echo $content["title"] ?>"></span>
                            </div>
                            <h3><?php echo $content["title"] ?></h3>
                            <div class="overlay-box">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <h3><?php echo $content["title"] ?></h3>
                                        <div class="text"><?php echo $content["text"] ?></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            <?php endif ?>
        </div>
    </div>
</section>