<?php 
    $section_3 = $this->section_3 ;
    $content = $section_3["content"] ;
?>

<!--Events Section-->
<section class="events-section" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/2.jpg);">
  <div class="auto-container">
      <!--Sec Title-->
        <div class="sec-title light centered aos-init aos-animate" data-aos="fade-up" data-aos-duration="700">
          <?php /* ?><div class="title">Participate With Us</div><?php */ ?>
          <h2><?php echo $section_3["category_text"] ?></h2>
        </div>
        <!--Events Carousel-->
        <div class="events-carousel owl-carousel owl-theme aos-init aos-animate" data-aos="fade-up" data-aos-duration="700">

          <?php if (!empty($content)): ?>
            <?php foreach ($content as $content): ?>
              <!--Event Block-->
              <div class="event-block">
                  <div class="inner-box clearfix">
                      <!--Image Column-->
                      <div class="image-column col-md-6 col-sm-12 col-xs-12">
                          <div class="image">
                              <img src="<?php echo $content["cover"]["url"] ?>" alt="<?php echo $content["title"] ?>" />
                            </div>
                        </div>
                        <!--Content Column-->
                      <div class="content-column col-md-6 col-sm-12 col-xs-12">
                          <div class="inner">
                                <div class="text"><?php echo $content["text"] ?></div>
                            </div>
                        </div>
                    </div>
              </div>
              <!--Event Block-->
            <?php endforeach ?>
          <?php endif ?>

        </div>
    </div>
</section>
<!--End Events Section-->
