<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Nouveau message</title>
</head>

<body>
    <?php 
        $datas = $this->datas ;
    ?>
    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <table cellpadding="20" cellspacing="0" width="600" align="center">
                    <?php /* ?>
                    <p>
                        Nouveau message de <strong><?php echo $datas["from"] ?></strong>
                    </p>
                    <?php */ ?>

                    <p><?php echo $datas["message"] ?></p>
                </table><!-- top message -->
            </td>
        </tr>
    </table><!-- wrapper -->
</body>
</html>