<!-- Main content -->
<?php 
    $slug =  Zend_Controller_Front::getInstance()->getRequest()->getParam('slug');
    $m = Application_Model_Module::getTitleModuleIdBySlug($slug) ;
?>

<div class="content">
    <h3 class="text-light"><?php echo $m["title"] ?></h3>

    <div class="outer">
        <div class=" align-cener">
            <a href="javascript:void(0)" class="btn btn-primary" onclick="window.location.href='/pages/modify/?do=add&slug=<?php echo $slug ?>'" title="Ajouter"><i class="font-plus"></i>Ajouter</a>
            <a href="javascript:void(0)" class="btn btn-danger massdelete" data-resource_type="pages" data-slug="<?php echo $slug ?>" title="Supprimer"><i class="font-trash"></i>Supprimer</a>
        </div>

    </div>

    <div class="outer mt-25px">
        <div class="panel">
            <div class="well" >
                <table class="table table-condensed" id="data-table" data-slug="<?php echo $slug ?>">
                    <thead>
                        <tr>
                            <th width="2%"><input type="checkbox" id="checkAll" name="checkAll" class="styled" /></th>
                            <th>Title</th>
                            <th>Text</th>
                            <th width="15%">Catégorie</th>
                            <th width="15%">Update time</th>
                            <th>Etat</th>
                            <th class="acenter" width="10%">Actions</th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td colspan="7" class="text-center">Chargement des données</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /main content -->