<?php 
	$id_item = Application_Class_Utils::idx($this->page, 'id', 0); 
    $slug =  Zend_Controller_Front::getInstance()->getRequest()->getParam('slug');
    $m = Application_Model_Module::getTitleModuleIdBySlug($slug) ;
?>


<!-- Main content -->
<div class="content">
    <h3 class="text-light"><?php echo $m["title"] ?></h3>

    <div class="outer mt-25px">
        <div class="panel">
	        <form method="post" action="" id="pages-form" class="form-horizontal form-to-validate">
	            <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->page, 'id', ''); ?>" id="id" name="<?php echo $slug ?>[id]">
	            <input type="hidden" value="<?php echo $slug ?>"  name="slug">

		    	<div class="row-fluid">
			    	<div class="span9">
			    		<div class="">
			    			<div class="box">
			    				<div class="tabbable">
		    						<?php Application_Class_Snippets::multilingualTabs(); ?>
			    					
			    					<div class="box">
	    							    <div class="well tab-form-content">
	    							    	<div class="control-group">
	    							    	    <label class="control-label" for="title"><span class="text-error">*</span> <?php echo $this->translate("Titre"); ?>:</label>
	    							    	    <div class="controls">
	    							    	        <?php 
	    							    	            $attributes = array(
	    							    	                'classic' => array(
	    							    	                    'id'            => 'title'
	    							    	                    ,'autocomplete' => 'off'
	    							    	                )
	    							    	                ,'custom' => array(
	    							    	                    'class'        => 'validate[required] span12 multilingual'
	    							    	                    ,'module'      => $slug
	    							    	                    ,'name'        => 'title'
	    							    	                    ,'data'        => $this->page
	    							    	                )
	    							    	            );
	    							    	            Application_Class_Forms::textMultilingual($attributes); 
	    							    	        ?>
	    							    	    </div>
	    							    	</div>

	    							    	<div class="control-group">
	    							    	    <label class="control-label" for="icon">&nbsp;Icône:</label>
	    							    	    <div class="controls">
	    							    	        <input type="text" name="<?php echo $slug ?>[icon]" id="icon" class="span12" value="<?php echo $this->page["icon"] ?>">
	    							    	    </div>
	    							    	</div>

	    						        	<div class="control-group">
	    						        	    <label class="control-label" for="text"> <?php echo $this->translate("Description"); ?>:</label>
	    						        	    <div class="controls">
	    						        	        <?php 
	    						        	            $attributes = array(
	    						        	                'classic' => array(
	    						        	                    'autocomplete' => 'off'
	    						        	                    ,'rows'         => 10
	    						        	                )
	    						        	                ,'custom' => array(
	    														'id'      => 'text'
	    														,'class'  => 'span12 multilingual ckeditor'
	    														,'module' => $slug
	    														,'name'   => 'text'
	    														,'data'   => $this->page
	    						        	                )
	    						        	            );
	    						        	            Application_Class_Forms::textareaMultilingual($attributes);
	    						        	            Application_Class_Ckeditor::initToggleCkeditor('text'); 
	    						        	        ?>
	    						        	    </div>
	    						        	</div>

	    						        	

	    							   	</div>
			    					</div>

									<div class="mt-25px"></div>

			   				   		<?php Application_Class_Forms::boxSeo($slug, $this->page); ?>

			    				</div>
			    			</div>
			    		</div>
				    </div>

				    <div class="span3">
			    	    <div class="well">
			    	    	<div class="navbar">
			    		        <div class="navbar-inner">
			    		            <h6><?php echo $this->translate("Publier"); ?></h6>
			    		        </div>
			    		    </div>

		    		    	<div class="control-group">
		    		    		<button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
		    		    		<button type="button" class="btn btn-danger ml5" onclick="window.location.href='/pages/?slug=<?php echo $slug ?>'"><?php echo $this->translate("Retour"); ?></button>
		    		    	</div>
			    		</div>

			    		<?php 
	    					Application_Class_Forms::boxCategory($slug, $this->page, 'pages_categories', 'id_page');
			    		?>

			    		<?php if ($this->do == "edit"): ?>
	    		    		<div class="well mt-25px"> 
	    		    			<div class="navbar"> 
	    		    				<div class="navbar-inner"> 
	    		    					<h6><?php echo $this->translate("Image à la Une"); ?></h6> 
	    		    				</div> 
	    		    			</div> 

			    				<div class="control-group">
		    					 	<div class="cover">
	                                    <?php
	                                    $cover_photo = Application_Model_Media::getCover("pages", $id_item); ?>

	                                    <?php if ($cover_photo): ?>
	                                        <div class="input-append" style="width:75%;margin-bottom:10px">
	                                            <input id="appendedInputButton" class="span12 input-block-level" type="text" value="<?php echo $cover_photo ?>" readonly>
	                                            <a class="btn" href="<?php echo $cover_photo ?>" target="_blank">Voir</a>
	                                        </div>
	                                    <?php endif ?>

	                                    <div class="clearfix"></div> 

	                                    <?php 
	                                        $id_media = Application_Model_Media::getCoverIdMedia("pages", $id_item);
	                                        if ($cover_photo) {
	                                            echo $this->partial("medias/sidebar/cover_photo.phtml", array("id_media" => $id_media, "id_item" => $id_item, "type" => "cover", "module" => "pages"));
	                                        } else {
	                                            echo $this->partial("medias/sidebar/add_cover.phtml", array("id_media" => 0, "id_item" => $id_item, "type" => "cover", "module" => "pages"));
	                                        }
	                                    ?>
	                                </div>
			    				</div>
	    		    		</div>
	    				<?php endif ?>
	    				
				   	</div>
				</div>

				<div class="mb60"></div>
	        </form>
        </div>
    </div>
</div>