<!-- Main content -->
<div class="content">
    <h3 class="text-light">Utilisateurs</h3>

    <div class="outer mt-25px">
        <div class="panel">
            <form method="post" action="" id="users-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->user, 'id', ''); ?>" id="id" name="Users[id]">

                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget">
                            <div class="well">
                                <div class="control-group">
                                    <label class="control-label" for="first_name"> Nom :</label>
                                    <div class="controls"><input type="text" class="span12 validate[required]" value="<?php echo Application_Class_Utils::idx($this->user, 'first_name', ''); ?>" id="first_name" name="Users[first_name]" /></div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="last_name"> Prénom :</label>
                                    <div class="controls"><input type="text" class="span12 validate[required]" value="<?php echo Application_Class_Utils::idx($this->user, 'last_name', ''); ?>" id="last_name" name="Users[last_name]" /></div>
                                </div>
                                
                                <div class="control-group">
                                    <label class="control-label" for="email"><span class="text-error">*</span> Email:</label>
                                    <div class="controls"><input type="text" class="validate[required, custom[email]] span12" value="<?php echo Application_Class_Utils::idx($this->user, 'email', ''); ?>" id="email" name="Users[email]" autocomplete="off" /></div>
                                </div>

                                <?php if($this->do=="edit"): ?>
                                    <div class="control-group">
                                        <label class="control-label" for="password"> Mot de passe:</label>
                                        <div class="controls" style="margin-top: 5px"><a href="<?php echo BASE_URL . '/resetpassword?email=' . $this->user['email'].'&hash='.$this->hash ?>">Veuillez cliquer pour générer un nouveau mot de passe</a></div>
                                    </div>
                                <?php else: ?>
                                    <div class="control-group">
                                        <label class="control-label" for="message"> Password:</label>
                                        <div class="controls" style="margin-top: 5px"><a>Un email vous sera envoyé pour définir votre mot de passe.</a></div>
                                    </div>    
                                <?php endif; ?>
                                
                                <div class="form-actions">
                                    <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                                    <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/users'"><?php echo $this->translate("Retour"); ?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mb30"></div>
            </form>
        </div>
    </div>
</div>