<!-- Content wrapper -->
<div class="wrapper">
<div class="crumbs">
  <ul id="breadcrumbs" class="breadcrumb"> 
      <li><a href=""><?php echo $this->translate("Tableau de bord"); ?></a></li>
  </ul>    
  <ul class="breadcrumb-right">
      <li><a target="_blank" href="/" title="<?php echo $this->translate("Visiter le site")?>"><i class="icon-home"></i><span><?php echo $this->translate("Visiter le site")?></span></a></li>
      <li><a href="/users" title="<?php echo $this->translate("Utilisateurs");?>"><i class="icon-user"></i>			<span><?php echo $this->translate("Utilisateurs")?></span></a></li>
			<li><a href="/siteconfiguration" title="<?php echo $this->translate("Configuration du site")?>"><i class="icon-cogs"></i><span><?php echo $this->translate("Configuration du site")?></span></a></li>
      </ul>      
  </ul>
</div>            
 <!-- Page header -->
    <div class="page-header">
    	<div class="page-title">
	    	<h2><?php echo $this->translate("Tableau de bord"); ?></h2>
    	</div>
        <ul class="page-stats">
          <li>
              <div class="showcase">
                  <span>New visits</span>
                  <h2>22.504</h2>
              </div>
              <div id="total-visits" class="chart">10,14,8,45,23,41,22,31,19,12, 28, 21, 24, 20</div>
          </li>
          <li>
              <div class="showcase">
                  <span>My balance</span>
                  <h2>$16.290</h2>
              </div>
              <div id="balance" class="chart">10,14,8,45,23,41,22,31,19,12, 28, 21, 24, 20</div>
          </li>
      </ul>
    </div>
    <!-- /page header -->
    
    <!-- Action tabs -->
    <div class="actions-wrapper">
        <div class="actions">
  
            <div id="user-stats">
                <ul class="round-buttons">
                    <li><div class="depth"><a href="#" title="Add new post" class="tip"><i class="icon-plus"></i></a></div></li>
                    <li><div class="depth"><a href="#" title="View statement" class="tip"><i class="icon-signal"></i></a></div></li>
                    <li><div class="depth"><a href="#" title="Media posts" class="tip"><i class="icon-reorder"></i></a></div></li>
                    <li><div class="depth"><a href="#" title="RSS feed" class="tip"><i class="icon-rss"></i></a></div></li>
                    <li><div class="depth"><a href="#" title="Create new task" class="tip"><i class="icon-tasks"></i></a></div></li>
                    <li><div class="depth"><a href="#" title="Layout settings" class="tip"><i class="icon-cogs"></i></a></div></li>
                </ul>
            </div>
  
            <div id="quick-actions">
                <ul class="statistics">
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="blue-square"><i class="icon-plus"></i></a>
                            <strong>12,476</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 60%;"></div></div>
                        <span>User registrations</span>
                    </li>
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="red-square"><i class="icon-hand-up"></i></a>
                            <strong>621,873</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 20%;"></div></div>
                        <span>Total clicks</span>
                    </li>
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="purple-square"><i class="icon-shopping-cart"></i></a>
                            <strong>562</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 90%;"></div></div>
                        <span>New orders</span>
                    </li>
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="green-square"><i class="icon-ok"></i></a>
                            <strong>$45,360</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 70%;"></div></div>
                        <span>General balance</span>
                    </li>
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="sea-square"><i class="icon-group"></i></a>
                            <strong>562K+</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 50%;"></div></div>
                        <span>Total users</span>
                    </li>
                    <li>
                        <div class="top-info">
                            <a href="#" title="" class="dark-blue-square"><i class="icon-facebook"></i></a>
                            <strong>36,290</strong>
                        </div>
                        <div class="progress progress-micro"><div class="bar" style="width: 93%;"></div></div>
                        <span>Facebook fans</span>
                    </li>
                </ul>
            </div>
  
            <!--<div id="map">
                <div id="google-map"></div>
            </div>-->
  
            <ul class="action-tabs">
                <li><a href="#user-stats" title="">Actions rapides</a></li>
                <li><a href="#quick-actions" title="">Statistiques du site</a></li>
               <!-- <li><a href="#map" title="" id="map-link">Google map</a></li>-->
            </ul>
        </div>
    </div>
    <!-- /action tabs -->
    <!-- Earnings stats widgets -->
    <div class="row-fluid">

        <div class="span4">
            <div class="widget">
                <div class="navbar"><div class="navbar-inner"><h6>Earnings statistic</h6></div></div>
                <div class="well body">
                    <ul class="stats-details">
                        <li>
                            <strong>Current balance</strong>
                            <span>latest update on 12:39 am</span>
                        </li>
                        <li>
                            <div class="number">
                                <a href="#" title="" data-toggle="dropdown"></a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#" title=""><i class="icon-refresh"></i>Reload data</a></li>
                                    <li><a href="#" title=""><i class="icon-calendar"></i>Change time period</a></li>
                                    <li><a href="#" title=""><i class="icon-cog"></i>Parameters</a></li>
                                    <li><a href="#" title=""><i class="icon-download-alt"></i>Download statement</a></li>
                                </ul>
                                <span>$6,458</span>
                            </div>
                        </li>
                    </ul>
                    <div class="graph" id="chart1" ></div>
                </div>
            </div>
        </div>

        <div class="span4">
            <div class="widget">
                <div class="navbar"><div class="navbar-inner"><h6>Visitor statistics</h6></div></div>
                <div class="well body">
                    <ul class="stats-details">
                        <li>
                            <strong>Today's visitors</strong>
                            <span>latest update on 4:42 pm</span>
                        </li>
                        <li>
                            <div class="number">
                                <a href="#" title="" data-toggle="dropdown"></a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#" title=""><i class="icon-refresh"></i>Reload data</a></li>
                                    <li><a href="#" title=""><i class="icon-calendar"></i>Change time period</a></li>
                                    <li><a href="#" title=""><i class="icon-cog"></i>Parameters</a></li>
                                    <li><a href="#" title=""><i class="icon-download-alt"></i>Download statement</a></li>
                                </ul>
                                <span>+12,127</span>
                            </div>
                        </li>
                    </ul>
                    <div class="graph" id="chart2"></div>
                </div>
            </div>
        </div>

        <div class="span4">
            <div class="widget">
                <div class="navbar"><div class="navbar-inner"><h6>Click statistics</h6></div></div>
                <div class="well body">
                    <ul class="stats-details">
                        <li>
                            <strong>Total clicks</strong>
                            <span>latest update on 3:09 pm</span>
                        </li>
                        <li>
                            <div class="number">
                                <a href="#" title="" data-toggle="dropdown"></a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="#" title=""><i class="icon-refresh"></i>Reload data</a></li>
                                    <li><a href="#" title=""><i class="icon-calendar"></i>Change time period</a></li>
                                    <li><a href="#" title=""><i class="icon-cog"></i>Parameters<strong class="badge badge-info">9</strong></a></li>
                                    <li><a href="#" title=""><i class="icon-download-alt"></i>Download statement</a></li>
                                </ul>
                                <span>168k+</span>
                            </div>
                        </li>
                    </ul>
                    <div class="graph" id="chart3"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- /earnings stats widgets -->

</div>    