<?php 
    // echo $this->partial("index/_partials/rev_slider_wrapper.phtml") ;
    echo $this->partial("index/_partials/hero-section.phtml") ;
?>

<!-- Main Content -->
<div id="main-content" class="site-main clearfix">
    <div id="content-wrap">
        <div id="site-content" class="site-content clearfix">
            <div id="inner-content" class="inner-content-wrap">
                <div class="page-content">

                    <?php 
                        echo $this->partial("index/_partials/promotion.phtml") ;
                        echo $this->partial("index/_partials/services.phtml") ;
                        echo $this->partial("index/_partials/works.phtml") ;
                        echo $this->partial("index/_partials/why-choose-us.phtml") ;
                        echo $this->partial("index/_partials/offer.phtml") ;
                        echo $this->partial("index/_partials/facts.phtml") ;
                        echo $this->partial("index/_partials/testimonials.phtml") ;
                    ?>
                    
                </div><!-- /.page-content -->
            </div>
        </div>
    </div>
</div>

        

