<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Récupération de votre mot de passe</title>
</head>

<body>
	<table width="100%" cellpadding="0" cellspacing="0">
		<tr>
			<td>
				<table cellpadding="20" cellspacing="0" width="600" align="center">
					Pour mettre en place votre nouveau mot de passe, veuillez cliquer sur le lien suivant <a href="<?php echo $this->url; ?>"><?php echo $this->url; ?></a>.
				</table><!-- top message -->
			</td>
		</tr>
	</table><!-- wrapper -->
</body>
</html>