<?php 
  echo $this->partial("_partials/page-title.phtml",array("page" => $this->translate("Qui sommes-nous ?"))) ;

  if (!empty($this->contents)) {
    $chunked_data = array_chunk($this->contents, sizeof($this->contents) / 2) ;

    foreach ($chunked_data[0] as $k => $data) {
      $phtml = ($k % 2 == 1) ? "right-image.phtml" : "left-image.phtml" ;
      echo $this->partial("pages/_partials/about/fullwidth-section/".$phtml,array("content" => $data)) ;
    }

  }

  if (!empty($this->testimonials)) {
    echo $this->partial("pages/_partials/about/testimonial-section.phtml",array("testimonials" => $this->testimonials)) ;
  }

  if (!empty($this->objectifs)) {
    echo $this->partial("pages/_partials/about/objectifs.phtml",array("objectifs" => $this->objectifs)) ;
  }

  if (!empty($this->teams)) {
    echo $this->partial("pages/_partials/about/team.phtml",array("teams" => $this->teams)) ;
  }

  foreach ($chunked_data[1] as $k => $data) {
    $phtml = ($k % 2 == 1) ? "right-image.phtml" : "left-image.phtml" ;
    echo $this->partial("pages/_partials/about/fullwidth-section/".$phtml,array("content" => $data)) ;
  }
?>