<?php 
	echo $this->partial("_partials/page-title.phtml",array("page" => $this->translate("Notre approche"))) ;

	if (!empty($this->section_1)) {
  		echo $this->partial("pages/_partials/approach/section-1.phtml",array("section_1" => $this->section_1)) ;
	}

	if (!empty($this->section_2)) {
  		foreach ($this->section_2 as $k => $data) {
      		$phtml = ($k % 2 == 1) ? "right-image.phtml" : "left-image.phtml" ;
	      	echo $this->partial("pages/_partials/approach/fullwidth-section/".$phtml,array("content" => $data)) ;
	    }
	}

	if (!empty($this->section_3)) {
			echo $this->partial("pages/_partials/approach/section-3.phtml",array("section_3" => $this->section_3)) ;
	}
?>