<?php echo $this->partial("_partials/page-title.phtml",array("page" => $this->translate("Qui sommes-nous"))) ?>

<!--Envirment Section-->
<section class="environment-section">
	<div class="auto-container">
    	<div class="row clearfix">
        	<!--Content Column-->
            <div class="content-column col-md-6 col-sm-12 col-xs-12">
            	<div class="content-inner">
                	<!--Sec Title-->
                	<div class="sec-title">
                		<div class="title">Let’s Promote the Ecology</div>
                        <h2><span>Give Back To The Nature & <br></span>Make Environment  Save</h2>
                    </div>
                    <div class="icons-block">
                    	<div class="icon flaticon-nature-1"></div>
                        <div class="icon flaticon-plant-1"></div>
                        <div class="icon flaticon-sprout"></div>
                    </div>
                    <div class="bold-text">Aorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod labore et dolore magna aliqua ust enim veniam.</div>
                    <div class="text">Quis nostrud exercitation ullamco laboris nisi uat aliquip commodo consequat. dolor in reprehenderit ein voluptate velit es cillum dolore fugiat nulla pariatur occaecat cupidatat non proidentas sunt culpa qui officia deserunt mollit anim uart perspiciatis unde omnis iste natus error.</div>
                </div>
            </div>
            <!--Image Column-->
            <div class="image-column clearfix col-md-6 col-sm-12 col-xs-12">
            	<div class="large-image">
                	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-3.jpg" alt="" />
                </div>
                <div class="small-image">
                	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/image-4.jpg" alt="" />
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Envirment Section-->

<!--Counter Section-->
<section class="counter-section-two style-two" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/1.jpg);">
	<div class="auto-container">
        <h2>Statistics about the GreenWave</h2>
        <!--Fun Facts Section -->
        <div class="fun-facts-section">
            <div class="row clearfix">
            
                <!--Column-->
                <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="inner">
                        <div class="content">
                            <div class="count-outer">
                                <span class="count-text" data-speed="3000" data-stop="100">0</span>k
                            </div>
                            <div class="counter-title">Funds Collected</div>
                        </div>
                    </div>
                </div>
                
                <!--Column-->
                <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="inner">
                        <div class="content">
                            <div class="count-outer">
                                <span class="count-text" data-speed="3000" data-stop="500">0</span>+
                            </div>
                            <div class="counter-title">Completed Events</div>
                        </div>
                    </div>
                </div>
                
                <!--Column-->
                <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="inner">
                        <div class="content">
                            <div class="count-outer">
                                <span class="count-text" data-speed="4000" data-stop="1780">0</span>+
                            </div>
                            <div class="counter-title">Our Volunteers</div>
                        </div>
                    </div>
                </div>
                
                <!--Column-->
                <div class="column count-box col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="inner">
                        <div class="content">
                            <div class="count-outer">
                                <span class="count-text" data-speed="3000" data-stop="120">0</span>+
                            </div>
                            <div class="counter-title">Awards Won</div>
                        </div>
                    </div>
                </div>
                    
            </div>
                
        </div>
        
    </div>
</section>
<!--End Counter Section-->

<!--Services Section-->
<section class="services-section-two style-two">
	<div class="auto-container">
    	<!--Sec Title-->
        <div class="sec-title centered">
        	<div class="title">Reasons to Help Us</div>
            <h2>Working Solutions</h2>
            <div class="text">Aorem ipsum dolor sit amet consectetur adipisicing elit usmod campor incididunt <br> labore temporg dolore magna aliqua ust enim sead minim veniam</div>
        </div>
        <div class="row clearfix">
			<!--Services Block Five-->
        	<div class="services-block-five col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                        <span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-1.png" alt="" /></span>
                    </div>
                    <h3>Recycling Waste</h3>
                    <div class="overlay-box">
                    	<div class="overlay-inner">
                        	<div class="content">
                            	<h3><a href="services.html">Recycling Waste</a></h3>
                                <div class="text">Dolore egua fugiat nulla pariatur sint occaecat cupidatat non proident tempor officia deserunt mollit anim laboum.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!--Services Block Five-->
        	<div class="services-block-five col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                        <span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-2.png" alt="" /></span>
                    </div>
                    <h3>Water Refining</h3>
                    <div class="overlay-box">
                    	<div class="overlay-inner">
                        	<div class="content">
                            	<h3><a href="services.html">Water Refining</a></h3>
                                <div class="text">Dolore egua fugiat nulla pariatur sint occaecat cupidatat non proident tempor officia deserunt mollit anim laboum.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!--Services Block Five-->
        	<div class="services-block-five col-md-4 col-sm-6 col-xs-12">
            	<div class="inner-box">
                	<div class="icon-box">
                        <span class="icon"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/service-icon-6.png" alt="" /></span>
                    </div>
                    <h3>Saving Plants</h3>
                    <div class="overlay-box">
                    	<div class="overlay-inner">
                        	<div class="content">
                            	<h3><a href="services.html">Saving Plants</a></h3>
                                <div class="text">Dolore egua fugiat nulla pariatur sint occaecat cupidatat non proident tempor officia deserunt mollit anim laboum.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
        <br>
        <div class="text-center">
        	<a href="services.html" class="theme-btn btn-style-four">view all</a>
        </div>
        
    </div>
</section>
<!--End Services Section-->

<!--Volunter Section-->
<section class="volunter-section grey-bg">
	<div class="auto-container">
    	<!--Sec Title-->
        <div class="sec-title centered">
        	<div class="title">Reasons to Join Us</div>
        	<h2>The Volunteers</h2>
        </div>
        <div class="row clearfix">
        	
            <!--Volunter Member-->
            <div class="volunter-member style-two col-md-6 col-sm-12 col-xs-12">
            	<div class="inner-box">
                	<div class="row clearfix">
                    	<!--Image Column-->
                    	<div class="image-column col-md-5 col-sm-5 col-xs-12">
                        	<div class="image">
                            	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-1.jpg" alt="" />
                                <div class="overlay-box">
                                	<ul class="social-icon-one">
                                    	<li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                    	<div class="content-column col-md-7 col-sm-7 col-xs-12">
                        	<div class="inner-column">
                            	<h3>William Hales</h3>
                                <div class="designation">Founder</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member style-two col-md-6 col-sm-12 col-xs-12">
            	<div class="inner-box">
                	<div class="row clearfix">
                    	<!--Image Column-->
                    	<div class="image-column col-md-5 col-sm-5 col-xs-12">
                        	<div class="image">
                            	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-2.jpg" alt="" />
                                <div class="overlay-box">
                                	<ul class="social-icon-one">
                                    	<li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                    	<div class="content-column col-md-7 col-sm-7 col-xs-12">
                        	<div class="inner-column">
                            	<h3>Arthur John</h3>
                                <div class="designation">Senior Admin</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member style-two col-md-6 col-sm-12 col-xs-12">
            	<div class="inner-box">
                	<div class="row clearfix">
                    	<!--Image Column-->
                    	<div class="image-column col-md-5 col-sm-5 col-xs-12">
                        	<div class="image">
                            	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-3.jpg" alt="" />
                                <div class="overlay-box">
                                	<ul class="social-icon-one">
                                    	<li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                    	<div class="content-column col-md-7 col-sm-7 col-xs-12">
                        	<div class="inner-column">
                            	<h3>Matilda Rose</h3>
                                <div class="designation">Volunteer</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
            <!--Volunter Member-->
            <div class="volunter-member style-two col-md-6 col-sm-12 col-xs-12">
            	<div class="inner-box">
                	<div class="row clearfix">
                    	<!--Image Column-->
                    	<div class="image-column col-md-5 col-sm-5 col-xs-12">
                        	<div class="image">
                            	<img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/volunter-4.jpg" alt="" />
                                <div class="overlay-box">
                                	<ul class="social-icon-one">
                                    	<li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!--Content Column-->
                    	<div class="content-column col-md-7 col-sm-7 col-xs-12">
                        	<div class="inner-column">
                            	<h3>Robyn Kate</h3>
                                <div class="designation">Volunteer</div>
                                <div class="text">Fugiat nulla pariatur excepteur sint occaecat acupidatat nodes proident sunt.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Volunter Member-->
            
        </div>
        
    </div>
</section>
<!--End Volunter Section-->

<!--Testimonial Section-->
<section class="testimonial-section">
	<div class="auto-container">
    	<div class="row clearfix">
        	
            <!--Column-->
            <div class="title-column col-md-4 col-sm-12 col-xs-12">
            	<div class="quote"><span class="icon flaticon-double-quotes"></span></div>
                <div class="sec-title">
                	<div class="title">What People Saying</div>
                    <h2>The Testimonials</h2>
                </div>
            </div>
            <!--Column-->
            <div class="column col-md-8 col-sm-12 col-xs-12">
            	<div class="single-item-carousel owl-theme owl-carousel">
                
                	<!--Testimonial Block-->
                	<div class="testimonial-block">
                    	<div class="inner-box">
                        	<div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                	<div class="testimonial-block">
                    	<div class="inner-box">
                        	<div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                	<div class="testimonial-block">
                    	<div class="inner-box">
                        	<div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                    <!--Testimonial Block-->
                	<div class="testimonial-block">
                    	<div class="inner-box">
                        	<div class="image"><img src="<?php echo THEMES_DEFAULT_URL ?>images/resource/author-1.jpg" alt="" /></div>
                            <h3>GreenWave are the Best Green Environment Supporters!</h3>
                            <div class="text">Consectetur adipisicing elit sed doloar eiusmod tempor incididunt ut labore et dolore magna aliqua suat enim minim venia quis nostrud exercitation ullamco laboris nisi utsed aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit inca voluptate velit esse cillum dolore eu fugiat nulla pariatur. </div>
                            <h4>benn Russel</h4>
                            <div class="designation">Our Donator</div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>
<!--End Testimonial Section-->

<!--Clients Section-->
<section class="clients-section style-two grey-bg">
	<div class="auto-container">
    	<!--Sponsors Carousel-->
        <ul class="sponsors-carousel owl-carousel owl-theme">
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/1.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/2.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/3.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/4.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/1.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/2.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/3.jpg" alt=""></a></figure></li>
            <li class="slide-item"><figure class="image-box"><a href="#"><img src="<?php echo THEMES_DEFAULT_URL ?>images/clients/4.jpg" alt=""></a></figure></li>
        </ul>
    </div>
</section>
<!--End Clients Section-->