<?php 
  echo $this->partial("_partials/page-title.phtml",array("page" => $this->translate("Mentions légales"))) ;
?>

<!--Testimonial Section-->
<section class="fullwidth-section aos-init aos-animate" data-aos="fade-in-up" data-aos-duration="700">
  <div class="section-outer clearfix">
      	<div class="content-column" style="width: 100% !important;padding-right: 80px !important">
      		<div class="content" style="max-width: 100% !important;">
      			<div class="text">
            	<?php echo $this->section_1["content"][0]["text"] ?>
      			</div>
      		</div>
        </div>
    </div>
</section>
<!--End Testimonial Section-->
