<!DOCTYPE html>
<!--[if IE 8]><html class="ie ie8"> <![endif]-->
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->
<html>
<!--<![endif]-->

<head>
	<?php 
	    echo $this->headTitle();
	?>
    <link rel='stylesheet' href='<?php echo THEMES_DEFAULT_URL ; ?>css/comingsoon.css' type='text/css' media='all' />
</head>

<body  data-gr-c-s-loaded="true" cz-shortcut-listen="true">
     <?php 
        echo $this->layout()->content;
    ?> 
</body>
</html>