<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

<?php
    echo $this->headMeta() . "\n";

    $site_name = Zend_Registry::get('option')->get('site_name');
    $this->headTitle()->setSeparator(', ');
    $this->headTitle($site_name." - Backoffice");
    echo $this->headTitle() . "\n";

    $this->headLink()       
        // IE 8
        ->prependStylesheet(THEMES_LOGIN_URL . 'css/ie8.css', 'screen', 'IE 8')

        // goole font Open Sans
        ->prependStylesheet("https://fonts.googleapis.com/css?family=Open+Sans:400,600,700")

        // bootstrap
        ->prependStylesheet(THEMES_LOGIN_URL . 'css/bootstrap.css');

    echo $this->headLink() . "\n";

    $this->headScript()
        // main login
        ->prependFile(THEMES_LOGIN_URL . 'js/main-login.js', 'text/javascript')
        
        // bootstrap
        ->prependFile(THEMES_LOGIN_URL . 'js/files/bootstrap.min.js', 'text/javascript')
        
        // uniform
        ->prependFile(THEMES_LOGIN_URL . 'js/plugins/forms/jquery.uniform.min.js', 'text/javascript')

        // JQuery UI
        ->prependFile(THEMES_LOGIN_URL . 'js/jquery-ui.min.js', 'text/javascript')

        // JQuery
        ->prependFile(THEMES_LOGIN_URL . 'js/jquery.1.8.3.min.js', 'text/javascript');

    echo $this->headScript() . "\n";
?> 
</head>

<body id="login" class="no-background" style="background: url('<?php echo THEMES_LOGIN_URL?>images/backgrounds/default.jpg');">
    <?php echo $this->layout()->content; ?>
</body>
</html>