<?php $id_item = Application_Class_Utils::idx($this->category, 'id', 0); ?>

<!-- Main content -->
<div class="content">
    <h3 class="text-light">Catégories</h3>

    <div class="outer mt-25px">
        <div class="panel">

            <?php  ?>
            <form method="post" action="" id="categories-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->category, 'id', ''); ?>" id="id" name="Categories[id]">
                <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->category, 'order_item', ''); ?>" id="id" name="Categories[old_order_item]">

                <div class="row-fluid">
                    <div class="span9">
                        <div class="well">
                            <div class="box">
                                <div class="tabbable"><!-- multilingual tabs -->
                                    <?php Application_Class_Snippets::multilingualTabs(); ?>

                                    <div class="box">
                                        <div class="well tab-form-content">
                                            <div class="control-group">
                                                <label class="control-label" for="title"><span class="text-error">*</span> Title:</label>
                                                <div class="controls">
                                                    <?php 
                                                        $attributes = array(
                                                            'classic' => array(
                                                                'id'            => 'title'
                                                                ,'autocomplete' => 'off'
                                                            )
                                                            ,'custom' => array(
                                                                'class'        => 'validate[required] span12 multilingual'
                                                                ,'module'      => 'Categories'
                                                                ,'name'        => 'title'
                                                                ,'data'        => $this->category
                                                            )
                                                        );
                                                        Application_Class_Forms::textMultilingual($attributes); 
                                                    ?>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="title"><span class="text-error">*</span>&nbsp;Courte déscription:</label>
                                                <div class="controls">
                                                    <?php
                                                    $attributes = array(
                                                        'classic' => array(
                                                            'id' => 'title'
                                                            , 'autocomplete' => 'off'
                                                        )
                                                        , 'custom' => array(
                                                            'class' => 'span12 multilingual'
                                                            , 'module' => 'Categories'
                                                            , 'name' => 'short_description'
                                                            , 'data' => $this->category
                                                        )
                                                    );
                                                    Application_Class_Forms::textMultilingual($attributes);
                                                    ?>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="id_category_group"><span class="text-error">*</span> Group:</label>
                                                <div class="controls">
                                                    <select class="styled validate[required] span12" id="id_category_group" name="Categories[id_category_group]">
                                                        <?php 
                                                            $modules_groups = Application_Model_Module::getModulesGroups();
                                                            $options = array(
                                                                'default' => array(
                                                                    'value'  => ""
                                                                    ,'title' => "Choisir un groupe"
                                                                )
                                                                ,'selected' => (!empty($this->category['id_category_group'])) ? $this->category['id_category_group'] : ''
                                                                ,'options'  => $modules_groups
                                                            );
                                                            Application_Class_Forms::optionsModulesGroups($options); 
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="order_item"> Order:</label>
                                                <div class="controls">
                                                    <select class="styled span12" id="order_item" name="Categories[order_item]">
                                                        <?php 
                                                            if($this->do=="edit"):
                                                                $categories = Application_Model_Category::getCategoryByIdCategoryGroup($this->category['id_category_group']);
                                                            else:
                                                                $categories = array();
                                                            endif;

                                                            $options = array(
                                                                'atfirst' => array(
                                                                    'value'  => 1
                                                                    ,'title' => "Au début"
                                                                )
                                                                ,'atend' => array(
                                                                    'title' => "A la fin"   
                                                                )
                                                                ,'optgrouplabel'     => "After"
                                                                ,'options'           => $categories
                                                                ,'tablename'         => TABLE_PREFIX.'categories'
                                                                ,'id_category_group' => (!empty($this->category['id_category_group'])) ? $this->category['id_category_group'] : ''
                                                            );
                                                            Application_Class_Forms::optionsOrderItemCategory($options); 
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="text"> Description:</label>
                                                <div class="controls">
                                                    <?php 
                                                        $attributes = array(
                                                            'classic' => array(
                                                                'autocomplete' => 'off'
                                                                ,'rows'        => 10
                                                            )
                                                            ,'custom' => array(
                                                                'id'      => 'text'
                                                                ,'class'  => 'span12 multilingual ckeditor'
                                                                ,'module' => 'Categories'
                                                                ,'name'   => 'text'
                                                                ,'data'   => $this->category
                                                            )
                                                        );
                                                        Application_Class_Forms::textareaMultilingual($attributes); 
                                                        Application_Class_Ckeditor::initToggleCkeditor('text'); 
                                                    ?>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="title"> ID:</label>
                                                <div class="controls">
                                                    <input type="text" id="uniqid" autocomplete="off" class="span12" name="Categories[uniqid]" value="<?php echo Application_Class_Utils::idx($this->category, 'uniqid', ''); ?>">
                                                </div>
                                            </div>
                                        </div>  
                                    </div>  

                                    <?php /*  Application_Class_Forms::boxSeo('Categories', $this->category); */ ?>
                                    
                                </div><!-- end multilingual tabs -->
                            </div>
                        </div>
                    </div>

                    <div class="span3">
                        <div class="well">
                            <div class="navbar">
                                <div class="navbar-inner">
                                    <h6>Publier</h6>
                                </div>
                            </div>

                            <div class="control-group">
                                <button class="btn btn-primary" type="submit">Enregistrer</button>
                                <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/categories'">Retour</button>
                            </div>
                        </div>

                        <?php if ($this->do == 'edit'): ?>
                            <div class="well mt-25px"> 
                                <div class="navbar"> 
                                    <div class="navbar-inner"> 
                                        <h6>Image à la Une</h6> 
                                    </div> 
                                </div> 
                                <div class="control-group">
                                     <div class="cover">
                                        <?php
                                        $cover_photo = Application_Model_Media::getCover("category", $id_item); ?>

                                        <?php if ($cover_photo): ?>
                                            <div class="input-append" style="width:75%;margin-bottom:10px">
                                                <input id="appendedInputButton" class="span12 input-block-level" type="text" value="<?php echo $cover_photo ?>" readonly>
                                                <a class="btn" href="<?php echo $cover_photo ?>" target="_blank">Voir</a>
                                            </div>
                                        <?php endif ?>

                                        <div class="clearfix"></div> 

                                        <?php 
                                            $id_media = Application_Model_Media::getCoverIdMedia("category", $id_item);
                                            if ($cover_photo) {
                                                echo $this->partial("medias/sidebar/cover_photo.phtml", array("id_media" => $id_media, "id_item" => $id_item, "type" => "cover", "module" => "category"));
                                            } else {
                                                echo $this->partial("medias/sidebar/add_cover.phtml", array("id_media" => 0, "id_item" => $id_item, "type" => "cover", "module" => "category"));
                                            }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>

                    </div>
                </div>

                <div class="mb60"></div>
            </form>
            <?php  ?>
        </div>
    </div>
</div>
<!-- /main content -->