<!--Comments Area-->
<?php 
    $_adapter = Application_Class_Utils::accessProtected($this->paginator,"_adapter") ;
    $comments = Application_Class_Utils::accessProtected($_adapter,"_array") ;
?>

<div class="comments-area">
    <div class="group-title <?php echo (empty($comments)) ? "mb-20px" : "" ?>"><h2><?php echo $this->translate("Commentaires") ?></h2></div>
    
    <!--Comment Box-->
    <div id="results_wrapper">
       
        <?php if (!empty($comments)){ ?>
            <?php foreach ($comments as $comment): ?>
                <div class="comment-box aos-init aos-animate" data-aos="fade-right" data-aos-duration="700">
                    <div class="comment">
                        <div class="author-thumb">
                            <img class="__initial__" src="" data-name="<?php echo $comment["author_name"] ?>" alt="<?php echo $comment["author_name"] ?>" width="70" height="70">
                        </div>
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <strong><?php echo $comment["author_name"] ?></strong>
                                <div class="comment-time">
                                    <?php 
                                        $t = $this->translate("Publié le #date_publication# à #time#") ;
                                        $t = str_replace("#date_publication#", $comment["publication_date"], $t) ; 
                                        $t = str_replace("#time#", $comment["create_time"], $t) ;
                                        echo $t ; 
                                    ?>
                                </div>
                            </div>
                            <div class="text"><?php echo $comment["comment"] ?></div>
                            <?php /* ?><a class="comment-reply" href="#">Reply</a><?php /*/ ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        <?php } else{ ?>
            <div class="alert alert-success"><?php echo $this->translate("Soyez le premier à laisser un commentaire") ?>&nbsp;😉</div>
        <?php } ?>

        <?php
            echo "<input type='hidden' name='__pagination__' data-resource_type='comments_news' data-resource_id='".$this->id_new."'>" ; 
            echo $this->paginator;
        ?>
    </div>
</div>