<!-- Main content -->
<div class="content">
    <h3 class="text-light">Traductions</h3>

    <div class="outer mt-25px">
        <div class="panel">

            <form method="post" action="" id="translations-form" class="form-horizontal form-to-validate">
                <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->translation, 'id_translation', ''); ?>" id="id" name="Translations[id]">
                <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->translation, 'id_language', ''); ?>" id="id_language" name="Translations[id_language]">

                <div class="row-fluid">
                    <div class="span12">
                        <div class="widget">
                            <div class="box">
                                <div class="tabbable">

                                    <div class="box">
                                        <div class="well tab-form-content">
                                            <div class="control-group">
                                                <label class="control-label" for="key"><?php echo ($this->do=="add") ? '<span class="text-error">*</span>' : "" ; ?> <?php echo $this->translate("Clé"); ?>:</label>
                                                <div class="controls">
                                                    <?php if($this->do=="add"): ?>
                                                        <input type="text" class="span12 <?php echo ($this->do=="add") ? 'validate[required]' : '' ; ?>" id="key" name="Translations[key]" value="<?php echo Application_Class_Utils::idx($this->translation, 'key', ''); ?>">
                                                    <?php 
                                                        else:
                                                            echo '<div style="margin-top: 5px">'.Application_Class_Utils::idx($this->translation, 'key', '').'</div>';
                                                        endif; 
                                                    ?>
                                                </div>
                                            </div>

                                            <?php if($this->do=="edit"): ?>
                                                <div class="control-group">
                                                    <label class="control-label" for="value"><span class="text-error">*</span> <?php echo $this->translate("Traduction"); ?>:</label>
                                                    <div class="controls">
                                                        <textarea class="span12 validate[required]" rows="4" name="Translations[value]" id="value"><?php echo Application_Class_Utils::idx($this->translation, 'value', ''); ?></textarea>
                                                    </div>
                                                </div>
                                            <?php endif; ?>

                                            <div class="form-actions">
                                                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                                                <button type="button" class="btn btn-danger ml5" onclick="window.location.href='/translations/index/id/<?php echo $this->id_language; ?>'"><?php echo $this->translate("Retour"); ?></button>
                                            </div>
                                        </div>  
                                    </div>  
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="mb60"></div>
            </form>
        </div>
    </div>
</div>
<!-- /main content -->