<script language="javascript">
	var baseUrl = "<?php echo $this->baseUrl(); ?>";
	var JS_MAX_SIZE_ALERT = "<?php echo $this->translate("Fichier trop volumineux") ?>";
	var JS_UNSUPPORTED_FILE = "<?php echo $this->translate("Fichier non supporté") ?>";
	var JS_MAX_SIZE = "<?php echo FILE_MAX_SIZE ?>";
	var JS_MAX_SIZE_ALERT = "<?php echo $this->translate("Fichier trop volumineux") ?>";

	/*swal*/
	var SWAL_CONFIRMATION = "<?php echo $this->translate("Êtes-vous sûr de supprimer cet élément ?") ?>";
	var SWAL_CONFIRMATIONS = "<?php echo $this->translate("Êtes-vous sûr de supprimer ces éléments ?") ?>";
	var SWAL_INFO = "<?php echo $this->translate("Vous ne pourrez pas revenir en arrière!") ?>";

</script>