<div class="content">
    <h3 class="text-light">Modules</h3>

    <div class="outer mt-25px">
        <div class="panel">
            <div class="row-fluid">
                <div class="span4">
                    <div class="well">
                        <div class="navbar">
                            <div class="navbar-inner">
                                <h6><?php echo $this->do; ?></h6>
                            </div>
                        </div>
                        <form method="post" action="" id="modules-form" class="form-horizontal form-to-validate">
                            <input type="hidden" value="<?php echo Application_Class_Utils::idx($this->module, 'id', ''); ?>" id="id" name="Modules[id]">

                            <div class="control-group">
                                <label for="title" class="control-label"><span class="text-error">*</span> <?php echo $this->translate("Nom"); ?>:</label>
                                <div class="controls"><input type="text" class="span12 validate[required]" id="title" name="Modules[title]" value="<?php echo Application_Class_Utils::idx($this->module, 'title', ''); ?>"></div>
                            </div>

                            <div class="form-actions align-right">
                                <button class="btn btn-primary" type="submit"><?php echo $this->translate("Enregistrer"); ?></button>
                                <button class="btn" type="reset"><?php echo $this->translate("Effacer"); ?></button>
                            </div>
                        </form>  
                    </div>
                </div>
                
                <div class="span8">
                    <!-- Default datatable -->
                    <div class="well">
                        <table class="table table-condensed" id="data-table">
                            <thead>
                                <tr>
                                    <th width="2%"></th>
                                    <th><?php echo $this->translate("Nom"); ?></th>
                                    <th><?php echo $this->translate("Slug"); ?></th>
                                    <th width=""><?php echo $this->translate("Date de modification"); ?></th>
                                    <th class="acenter" width="10%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="5" class="text-center">Chargement des données</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <!-- /default datatable -->
                </div>
            </div>
        </div>
    </div>
</div>