<!-- Main content -->
<div class="content">
    <h3 class="text-light">Contacts</h3>

    <div class="outer">
        <div class=" align-cener">
            <a href="javascript:void(0)" class="btn btn-danger massdelete" data-resource_type="contacts" title="Supprimer"><i class="font-trash"></i>Supprimer</a>
        </div>

    </div>

    <div class="outer mt-25px">
        <div class="panel">
            <div class="well" >
                <table class="table table-condensed" id="data-table">
                    <thead>
                        <tr>
                            <th width="2%"><input type="checkbox" id="checkAll" name="checkAll" class="styled" /></th>
                            <th width="15%"><?php echo $this->translate("Nom");?></th> <!-- id_seo -->
                            <th><?php echo $this->translate("Email");?></th>
                            <th><?php echo $this->translate("Message");?></th>
                            <th><?php echo $this->translate("Date de création");?></th>
                            <th class="acenter" width="5%"><?php echo $this->translate("Actions");?></th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td colspan="6" class="text-center">Chargement des données</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /main content -->