<!-- Stylesheet -->
<link href="<?php echo THEMES_ERROR_URL ?>css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_ERROR_URL ?>css/jquery-ui.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_ERROR_URL ?>css/animate.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_ERROR_URL ?>css/css-plugin-collections.css" rel="stylesheet"/>
<!-- CSS | menuzord megamenu skins -->
<link id="menuzord-menu-skins" href="<?php echo THEMES_ERROR_URL ?>css/menuzord-skins/menuzord-boxed.css" rel="stylesheet"/>
<!-- CSS | Main style file -->
<link href="<?php echo THEMES_ERROR_URL ?>css/style-main.css" rel="stylesheet" type="text/css">
<!-- CSS | Preloader Styles -->
<link href="<?php echo THEMES_ERROR_URL ?>css/preloader.css" rel="stylesheet" type="text/css">
<!-- CSS | Custom Margin Padding Collection -->
<link href="<?php echo THEMES_ERROR_URL ?>css/custom-bootstrap-margin-padding.css" rel="stylesheet" type="text/css">
<!-- CSS | Responsive media queries -->
<link href="<?php echo THEMES_ERROR_URL ?>css/responsive.css" rel="stylesheet" type="text/css">
<!-- CSS | Style css. This is the file where you can place your own custom css code. Just uncomment it and use it. -->
<!-- <link href="<?php echo THEMES_ERROR_URL ?>css/style.css" rel="stylesheet" type="text/css"> -->

<!-- CSS | Theme Color -->
<link href="<?php echo THEMES_ERROR_URL ?>css/colors/theme-skin-green.css" rel="stylesheet" type="text/css">