<!-- external javascripts -->
<script src="<?php echo THEMES_ERROR_URL ?>js/jquery-2.2.4.min.js"></script>
<script src="<?php echo THEMES_ERROR_URL ?>js/jquery-ui.min.js"></script>
<script src="<?php echo THEMES_ERROR_URL ?>js/bootstrap.min.js"></script>
<!-- JS | jquery plugin collection for this theme -->
<script src="<?php echo THEMES_ERROR_URL ?>js/jquery-plugin-collection.js"></script>
<script src="<?php echo THEMES_ERROR_URL ?>js/custom.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->