<?php 
    $content = $this->content ;
?>

<section class="fullwidth-section">
    <div class="section-outer clearfix">
        <div class="image-column aos-init aos-animate" data-aos="fade-right" data-aos-duration="700" style="background-image:url(<?php echo $content["cover"]["url"] ?>);">
            <div class="hidden-image"><img src="<?php echo $content["cover"]["url"] ?>" alt="<?php echo $content["title"] ?>"></div>
        </div>
        <div class="content-column aos-init aos-animate" data-aos="fade-left" data-aos-duration="700">
            <div class="content">
                <div class="text">
                    <h2><?php echo $content["title"] ?></h2>
                    <?php echo $content["text"] ?>
                </div>
            </div>
        </div>
    </div>
</section>