<style type="text/css">
    div.text ul li{list-style: inside !important;}
</style>

<?php 
    $content = $this->content ;
?>

<section class="content-section aos-init aos-animate" data-aos="fade-right" data-aos-duration="700">
	<div class="auto-container">
    	<div class="row clearfix">
        	<div class="column col-md-5 col-sm-12 col-xs-12">
                <h3><?php echo $content["title"] ?></h3>
            </div>
            <div class="column col-md-7 col-sm-12 col-xs-12">
                <?php echo $content["text"] ?>
                </div>
            </div>
        </div>
    </div>
</section>