<?php 
    $version = Zend_Registry::get('version');
?>

<link href="<?php echo THEMES_LOGIN_URL ?>css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_LOGIN_URL ?>css/londinium-theme.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_LOGIN_URL ?>css/styles.css" rel="stylesheet" type="text/css">
<link href="<?php echo THEMES_LOGIN_URL ?>css/icons.css" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">

<!-- custom -->
<link rel="stylesheet" href="<?php echo THEMES_ADMIN_URL ?>css/app.css?v=<?php echo $version ;?>"/>
<link rel="stylesheet" href="<?php echo THEMES_ADMIN_URL ?>css/spacing-and-height.css"/>

<link rel="stylesheet" href="<?php echo PLUGINS_URL ; ?>jquery.growl/css/jquery.growl.css"/>

<link rel="stylesheet" href="<?php echo PLUGINS_URL ; ?>ladda/css/ladda.min.css"/>

<!-- datepicker -->
<link rel='stylesheet' href='<?php echo PLUGINS_URL; ?>bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css?v=<?php echo $version?>' type='text/css' media='all' />

<link rel='stylesheet' href='<?php echo PLUGINS_URL; ?>magnific-popup/dist/magnific-popup.css' type='text/css' media='all' />

<!-- font -->
<!-- <link rel="stylesheet" href="<?php echo THEMES_LOGIN_URL ?>icons/font-awesome/css/fontawesome-all.min.css"/>  -->
<link rel="stylesheet" href="<?php echo THEMES_LOGIN_URL ?>icons/fontawesome-free/css/all.min.css"/>
<link rel="stylesheet" href="<?php echo THEMES_LOGIN_URL ?>icons/material-design-iconic-font/css/material-design-iconic-font.min.css"/>
<link rel="stylesheet" href="<?php echo THEMES_LOGIN_URL ?>icons/simplelineicons.github.io-master/css/simple-line-icons.css"/>

<!-- sweet alert -->
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/sweetalert.css?v=<?php echo $version?>">
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>swal/themes/google/google.css?v=<?php echo $version?>">

<!-- toastr -->
<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS_URL ?>toastr/2.1.3/toastr.min.css">
