<?php 
    $version = Zend_Registry::get('version');
?>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/libs/jquery/1.10.1/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/charts/sparkline.min.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/uniform.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/select2.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/inputmask.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/autosize.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/inputlimit.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/listbox.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/multiselect.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/validate.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/tags.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/switch.min.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/uploader/plupload.full.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/uploader/plupload.queue.min.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/wysihtml5/wysihtml5.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/forms/wysihtml5/toolbar.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/interface/moment.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/interface/jgrowl.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/interface/datatables.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/plugins/interface/colorpicker.js"></script>

<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_LOGIN_URL?>js/application.js?v=<?php echo $version?>"></script>

<!-- custom -->
<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>autosize.min.js'></script>

<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>inputmask/dist/min/jquery.inputmask.bundle.min.js?v=<?php echo $version?>'></script>

<script type="text/javascript" src="<?php echo PLUGINS_URL ; ?>ladda/js/spin.min.js"></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL ; ?>ladda/js/ladda.min.js"></script>

<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>jquery.growl/js/jquery.growl.js'></script>
<!-- datepicker -->
<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js?v=<?php echo $version?>'></script>
<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>bootstrap-datepicker/dist/locales/bootstrap-datepicker.fr-CH.min.js?v=<?php echo $version?>'></script>

<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>magnific-popup/dist/jquery.magnific-popup.min.js'></script>

<?php /* ?><script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>jquery.matchHeight.js'></script><?php */ ?>
<script type='text/javascript' src='<?php echo PLUGINS_URL ; ?>jquery.matchHeight-min.js'></script>

<!-- sweet alert -->
<script type='text/javascript' src="<?php echo PLUGINS_URL; ?>swal/sweet_alert.min.js"></script>

<!-- toastr -->
<script type='text/javascript' src="<?php echo PLUGINS_URL; ?>toastr/2.1.3/toastr.min.js"></script>


<script src="<?php echo THEMES_ADMIN_URL ?>js/formvalidation.js?v=<?php echo $version?>"></script>
<script src="<?php echo THEMES_ADMIN_URL ?>js/app.js?v=<?php echo $version?>"></script>