<?php 
  $User = new Application_Model_User("admin") ;
  $id_user = $User->getId() ;
  $profilePicture = $User->getProfilePicture($id_user) ;

  $option = Zend_Registry::get("option") ;
?>

<!-- Top nav -->
<div id="top">
    <div class="top-wrapper">
        <a href="<?php echo $this->baseUrl() ?>/" title="<?php echo $option->site_name ?>" class="logo-text"><?php echo $option->site_name ?></a>
        <ul class="topnav">
            <li class="topuser">
                <a title="" data-toggle="dropdown"><span>Bienvenue&nbsp;<?php echo $profilePicture["full_name"] ?></span><i class="caret"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->baseUrl() ?>/users/modify/do/edit/id/<?php echo $id_user ?>" title=""><span class="user-profile"></span>Mon profil</a></li>
                    <?php /* ?>
                    <li><a href="#" title=""><span class="user-stats"></span>Statistics <strong>2</strong></a></li>
                    <li><a href="#" title=""><span class="user-settings"></span>Switch user</a></li>
                    <li><a href="#" title=""><span class="user-logout"></span>Logout</a></li>
                    <?php */ ?>
                </ul>
            </li>
            <?php /* ?><li><a href="#" title=""><b class="settings"></b></a></li><?php */ ?>
            <li><a href="<?php echo $this->baseUrl() ?>/siteconfiguration" title="Configuration du site"><b class="settings"></b></a></li>
            <li class="sidebar-button"><a href="#" title=""><b class="responsive-nav"></b></a></li>
            <li><a href="<?php echo $this->baseUrl() ?>/logout" title="Déconnexion"><b class="logout"></b></a></li>
        </ul>
    </div>
</div>
<!-- /top nav -->