<table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
  <tbody>
    <tr>
      <td class="pc-features-box-s1" style="vertical-align: top; padding: 40px 20px; background-color: #ffffff;" valign="top" bgcolor="#ffffff">
        <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
          <tbody>
            <tr>
              <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 24px; font-weight: 700; line-height: 1.42; letter-spacing: -0.4px; color: #151515; padding: 0 20px;" valign="top">Features.</td>
            </tr>
            <tr>
              <td style="vertical-align: top;" valign="top">
                <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                  <tbody>
                    <tr>
                      <td style="vertical-align: top; height: 10px; font-size: 10px; line-height: 10px;" valign="top">&nbsp;</td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 300; line-height: 1.56; letter-spacing: -0.2px; color: #9B9B9B; padding: 0 20px;" valign="top"> Co-ordinate campaigns and product launches, <br>with improved overall communication. </td>
            </tr>
            <?php /* ?>

            <tr>
              <td style="vertical-align: top;" valign="top">
                <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                  <tbody>
                    <tr>
                      <td style="vertical-align: top; height: 20px; font-size: 20px; line-height: 20px;" valign="top">&nbsp;</td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td>
                <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                  <tbody>
                    <tr>
                      <td class="pc-features-row-s1" style="vertical-align: top; font-size: 0;" valign="top">
                        <!--[if (gte mso 9)|(IE)]>
          <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                  <td width="33%" valign="top">
          <![endif]-->
                        <div class="pc-features-row-col" style="display: inline-block; width: 100%; max-width: 186px; vertical-align: top;">
                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                            <tbody>
                              <tr>
                                <td style="vertical-align: top; padding: 20px;" valign="top">
                                  <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                    <tbody>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top"> <img src="<?php echo Zend_Registry::get("option")->company_site ?>/public/themes/default/images/email/images/feature-1-image-1.jpg" width="48" height="48" alt="" style="border: 0; line-height: 100%; outline: 0; -ms-interpolation-mode: bicubic; display: block; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; color: #1B1B1B;"> </td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 10px; font-size: 10px; line-height: 10px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 500; line-height: 1.33; letter-spacing: -0.2px; color: #1B1B1B;" valign="top">Responsive</td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 6px; font-size: 6px; line-height: 6px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 300; line-height: 1.43; letter-spacing: -0.2px; color: #9B9B9B;" valign="top">Kogi Cosby sweater ethical squid irony disrupt, organic tote.</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if (gte mso 9)|(IE)]>
          </td>
          <td width="33%" valign="top">
          <![endif]-->
                        <div class="pc-features-row-col" style="display: inline-block; width: 100%; max-width: 186px; vertical-align: top;">
                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                            <tbody>
                              <tr>
                                <td style="vertical-align: top; padding: 20px;" valign="top">
                                  <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                    <tbody>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top"> <img src="<?php echo Zend_Registry::get("option")->company_site ?>/public/themes/default/images/email/images/feature-1-image-2.jpg" width="48" height="48" alt="" style="border: 0; line-height: 100%; outline: 0; -ms-interpolation-mode: bicubic; display: block; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; color: #1B1B1B;"> </td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 10px; font-size: 10px; line-height: 10px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 500; line-height: 1.33; letter-spacing: -0.2px; color: #1B1B1B;" valign="top">Clean code</td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 6px; font-size: 6px; line-height: 6px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 300; line-height: 1.43; letter-spacing: -0.2px; color: #9B9B9B;" valign="top">Kogi Cosby sweater ethical squid irony disrupt, organic tote.</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if (gte mso 9)|(IE)]>
          </td>
          <td width="33%" valign="top">
          <![endif]-->
                        <div class="pc-features-row-col" style="display: inline-block; width: 100%; max-width: 186px; vertical-align: top;">
                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                            <tbody>
                              <tr>
                                <td style="vertical-align: top; padding: 20px;" valign="top">
                                  <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                    <tbody>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top"> <img src="<?php echo Zend_Registry::get("option")->company_site ?>/public/themes/default/images/email/images/feature-1-image-3.jpg" width="48" height="48" alt="" style="border: 0; line-height: 100%; outline: 0; -ms-interpolation-mode: bicubic; display: block; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; color: #1B1B1B;"> </td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 10px; font-size: 10px; line-height: 10px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 500; line-height: 1.33; letter-spacing: -0.2px; color: #1B1B1B;" valign="top">Clean design</td>
                                      </tr>
                                      <tr>
                                        <td style="vertical-align: top;" valign="top">
                                          <table border="0" cellpadding="0" cellspacing="0" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                                            <tbody>
                                              <tr>
                                                <td style="vertical-align: top; height: 6px; font-size: 6px; line-height: 6px;" valign="top">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td class="pc-fb-font" style="vertical-align: top; font-family: 'Fira Sans', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 300; line-height: 1.43; letter-spacing: -0.2px; color: #9B9B9B;" valign="top">Kogi Cosby sweater ethical squid irony disrupt, organic tote.</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </div>
                        <!--[if (gte mso 9)|(IE)]>
          </td></tr></table>
          <![endif]-->
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <?php */ ?>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>