<div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr><td height='30'></td></tr>
    <tr>
      <td align='left'>
        <div class="contentEditableContainer contentTextEditable">
          <div class="contentEditable" align='center'>
            <h2><?php echo str_replace("#full_name#", $this->full_name, "Nouveau message de #full_name#") ?></h2>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td align='left'>
        <div class="contentEditableContainer contentTextEditable">
          <div class="contentEditable" align='center'>
            <p><?php echo $this->message ?></p>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>