<!--Map Section-->
<section class="map-section">
	<!--Map Outer-->
    <div class="map-outer">

        <div id="map"
            data-zoom="8"
            data-lat="-37.817085"
            data-lng="144.955631"
            data-type="roadmap"
            data-hue="#ffc400"
            data-title="Envato"
            data-icon-path="<?php echo THEMES_DEFAULT_URL ?>images/icons/map-marker.png"
            data-content="Melbourne VIC 3000, Australia<br><a href='mailto:info@youremail.com'>info@youremail.com</a>" style="height:500px">
        </div>

        <!--Map Canvas-->
        <?php /* ?>
        <div class="map-canvas"
            data-zoom="8"
            data-lat="-37.817085"
            data-lng="144.955631"
            data-type="roadmap"
            data-hue="#ffc400"
            data-title="Envato"
            data-icon-path="<?php echo THEMES_DEFAULT_URL ?>images/icons/map-marker.png"
            data-content="Melbourne VIC 3000, Australia<br><a href='mailto:info@youremail.com'>info@youremail.com</a>">
        </div>
        <?php */ ?>
    </div>
</section>
<!--End Map Section-->