<!--Subscribe section-->
<section class="subscribe-section" style="background-image:url(<?php echo THEMES_DEFAULT_URL ?>images/background/3.jpg);">
    <div class="auto-container">
        <div class="row clearfix">
            <!--Column-->
            <div class="column col-md-7 col-md-12 col-xs-12">
                <div class="text">Stay in Touch with us by ...</div>
                <h2>Subscribe to our Newsletter</h2>
            </div>
            <!--Column-->
            <div class="column col-md-5 col-md-12 col-xs-12">
                
                <!--Subscribe form-->
                <div class="subscribe-form">
                    <form method="post" action="http://t.commonsupport.xyz/greenwave/contact.html">
                        <div class="form-group">
                            <input type="email" name="email" value="" placeholder="Your email..." required>
                            <button type="submit" class="theme-btn">Send</button>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>
</section>
<!--End Subscribe section-->