<!-- Load page -->
<div class="animationload">
    <div class="loader"></div>
</div>
<!-- End load page -->


<!-- Content Wrapper -->
<div id="wrapper">

    <!-- Constraction -->
    <div class="constraction">
        <canvas id="canvas" class="construction-canvas" width="460" height="380" style="display: block; background-color:rgba(255, 255, 255, 1.00)"></canvas>
    </div>
    <!-- End Constraction -->

    <h3 class="title">Our Website Is Under Construction</h3>

    <!-- Watch -->
    <div id="watch">

        <!-- Days -->
        <div class="dash days_dash">
            <div class="digit day_field">0</div>
            <div class="digit">0</div>
            <div class="digit">6</div>
            <span class="dash_title">Days</span>
        </div>
        <!-- End Days -->

        <!-- Hours -->
        <div class="dash hours_dash">
            <div class="digit">1</div>
            <div class="digit">2</div>
            <span class="dash_title">Hours</span>
        </div>
        <!-- End Hours -->

        <!-- Minutes -->
        <div class="dash minutes_dash">
            <div class="digit">0</div>
            <div class="digit">5</div>
            <span class="dash_title">Minutes</span>
        </div>
        <!-- End Minutes -->

        <!-- Seconds -->
        <div class="dash seconds_dash">
            <div class="digit">3</div>
            <div class="digit">9</div>
            <span class="dash_title">Seconds</span>
        </div>
        <!-- End Seconds -->

    </div>
    <!-- End Watch -->

</div>
<!-- end Content Wrapper -->

<!-- Footer -->
<footer id="footer">
    <div class="container">

        <!-- footer socials -->
        <div class="row">

            <div class="footer_socials col-sm-12 text-center">

                <div class="contact_icons">
                    <ul class="contact_socials clearfix">
                        <!-- social icons -->
                        <li><a class="ukie_social" href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a class="ukie_social" href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a class="ukie_social" href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a class="ukie_social" href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a class="ukie_social" href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a class="ukie_social" href="#"><i class="fa fa-youtube"></i></a></li>
                        <!--
                            <li><a class="ukie_social" href="#"><i class="fa fa-behance"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-pinterest"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-digg"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-deviantart"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-envelope-square"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-delicious"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-instagram"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-dropbox"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-skype"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-tumblr"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-vimeo-square"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-flickr"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-github-alt"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-renren"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-vk"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-xing"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-weibo"></i></a></li>
                            <li><a class="ukie_social" href="#"><i class="fa fa-rss"></i></a></li>
                        -->
                    </ul>
                </div>

                <div class="copyright">@ 2016 All Right Reserved</div>

            </div>

        </div>
        <!-- end footer socials -->

    </div>
    <!-- end container -->
</footer>
<!-- end footer -->