<?php 
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $resource = $request->getControllerName();
    $action  = $request->getActionName();

    $option = Zend_Registry::get("option") ;
?>

<div id="site-header-wrap">
    <!-- Top Bar -->
    <div id="top-bar" class="style-2">
        <div id="top-bar-inner" class="container">
            <div class="top-bar-inner-wrap">
                
                <div class="top-bar-socials">
                    <div class="inner">
                        <span class="icons">
                            <a href="<?php echo $option->company_link_facebook ?>" target="_blank" title="Facebook"><span class="fa fa-facebook" aria-hidden="true"></span></a>

                            <?php /* ?>
                            <a href="<?php echo $option->company_link_facebook ?>" target="_blank" title="Twitter"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            <a href="<?php echo $option->company_link_facebook ?>" target="_blank" title="Google Plus"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                            <a href="<?php echo $option->company_link_facebook ?>" target="_blank" title="Pinterest"><span class="fa fa-pinterest" aria-hidden="true"></span></a>
                            <a href="<?php echo $option->company_link_facebook ?>" target="_blank" title="Dribbble"><span class="fa fa-dribbble" aria-hidden="true"></span></a>
                            <?php */ ?>
                        </span>
                    </div>
                </div><!-- /.top-bar-socials -->

                <div class="top-bar-content">
                    <span id="top-bar-text">
                        <i class="fa fa-phone-square"></i><?php echo $option->phone_number ?>
                        <i class="fa fa-envelope"></i><?php echo str_replace("@", "[@]", $option->company_email) ?>
                        <i class="fa fa-clock-o"></i>Mon-Fri: 7:00 - 17:00
                    </span><!-- /#top-bar-text -->
                </div><!-- /.top-bar-content -->
            </div>
        </div>
    </div><!-- /#top-bar -->

    <!-- Header -->
    <header id="site-header" class="header-front-page style-5">
        <div id="site-header-inner" class="container">
            <div class="wrap-inner">          
                <div id="site-logo" class="clearfix">
                    <div id="site-logo-inner">
                        <a href="home-slider-full-screen.html" title="Construction" rel="home" class="main-logo">
                            <img src="<?php echo THEMES_DEFAULT_URL?>/img/logo-light.png" alt="Construction" data-retina="<?php echo THEMES_DEFAULT_URL?>/img/logo-light@2x.png" data-width="200" data-height="30">
                        </a>
                    </div>
                </div><!-- /#site-logo -->

                <div class="mobile-button"><span></span></div><!-- //mobile menu button -->

                <nav id="main-nav" class="main-nav">
                    <ul class="menu">
                        <li class="menu-item menu-item-has-children current-menu-item"><a href="home-slider-full-screen.html">Home</a>
                            <ul class="sub-menu">
                                <li class="menu-item"><a href="home-slider-full-screen.html">Home 1 - Full Slider</a></li>
                                <li class="menu-item"><a href="home-slider-simple.html">Home 1 - Simple Slider</a></li>
                                <li class="menu-item"><a href="home-hero-slideshow.html">Home 1 - Slideshow 1</a></li>
                                <li class="menu-item"><a href="home-hero-slideshow-2.html">Home 1 - Slideshow 2</a></li>
                                <li class="menu-item"><a href="home-header-fixed.html">Home 1 - Header Fixed</a></li>
                                <li class="menu-item"><a href="home-2-slider-simple.html">Home 2 - Simple Slider</a></li>
                                <li class="menu-item"><a href="home-3-hero-slideshow.html">Home 3 - Slideshow</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-has-children"><a href="#">Pages</a>
                            <ul class="sub-menu">
                                <li class="menu-item"><a href="page-contact.html">Contact</a></li>
                                <li class="menu-item"><a href="page-about.html">About Us</a></li>
                                <li class="menu-item"><a href="page-about-2.html">About Us 2</a></li>
                                <li class="menu-item"><a href="page-services.html">Services</a></li>
                                <li class="menu-item"><a href="page-services-2.html">Services 2</a></li>
                                <li class="menu-item"><a href="page-service-detail.html">Service Detail</a></li>
                                <li class="menu-item"><a href="page-shop.html">Shop</a></li>
                                <li class="menu-item"><a href="page-shop-single.html">Shop Single</a></li>
                                <li class="menu-item"><a href="page-shop-cart.html">Shop Cart</a></li>
                                <li class="menu-item"><a href="blog-single.html">Blog Single</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-has-children"><a href="#">Elements</a>
                            <ul class="sub-menu">
                                <li class="menu-item"><a href="icons.html">Construction Icons</a></li>
                                <li class="menu-item"><a href="buttons.html">Buttons</a></li>
                                <li class="menu-item"><a href="toggles.html">Toggles</a></li>
                                <li class="menu-item"><a href="typography.html">Typography</a></li>
                                <li class="menu-item"><a href="galleries.html">Galleries</a></li>
                                <li class="menu-item"><a href="iconboxs.html">IconBoxs</a></li>
                            </ul>
                        </li>
                        <li class="menu-item menu-item-has-children"><a href="#">Portfolio</a>
                            <ul class="sub-menu">
                                <li class="menu-item"><a href="page-portfolio-grid.html">Grid</a></li>
                                <li class="menu-item"><a href="page-portfolio-grid-fullwidth.html">Grid Full-Width</a></li>
                                <li class="menu-item"><a href="page-portfolio-slider.html">Slider</a></li>
                                <li class="menu-item"><a href="page-portfolio-slider-fullwidth.html">Slider Full-Width</a></li>
                                <li class="menu-item"><a href="page-project-detail.html">Project Detail 1</a></li>
                                <li class="menu-item"><a href="page-project-detail-2.html">Project Detail 2</a></li>
                                <li class="menu-item"><a href="page-project-detail-3.html">Project Detail 3</a></li>
                                <li class="menu-item"><a href="page-project-detail-4.html">Project Detail 4</a></li>                               
                            </ul>
                        </li>
                        <li class="menu-item"><a href="blog.html">Blog</a></li>
                        <li class="menu-item"><a href="page-contact.html">Contact</a></li>
                    </ul>
                </nav><!-- /#main-nav -->

                <div id="header-search">
                    <a class="header-search-icon" href="#"><span class="fa fa-search"></span></a>

                    <form role="search" method="get" class="header-search-form" action="#">
                        <input type="text" value="" name="s" class="header-search-field" placeholder="Type and hit enter...">
                        <button type="submit" class="header-search-submit" title="Search">Search</button>
                        <input type="hidden" name="post_type" value="post">
                    </form>
                </div><!-- /#header-search -->

                <div class="nav-top-cart-wrapper">
                    <a class="nav-cart-trigger" href="#">
                        <span class="fa fa-shopping-cart cart-icon">
                            <span class="shopping-cart-items-count">3</span>
                        </span>
                    </a>

                    <div class="nav-shop-cart">
                        <div class="widget_shopping_cart_content">
                            <ul class="cart_list product_list_widget ">
                                <li class="mini_cart_item">
                                    <a href="#" class="remove" title="Remove this item">×</a>
                                    <a href="#">
                                        <img width="160" height="160" src="<?php echo THEMES_DEFAULT_URL?>/img/shop-item.png" alt="image">
                                        Shop Item 01
                                    </a>
                                                
                                    <span class="quantity">1 × <span class="woocommerce-Price-amount amount">
                                        <span class="woocommerce-Price-currencySymbol">$</span>200.00</span>
                                    </span>
                                </li>
                                <li class="mini_cart_item">
                                    <a href="#" class="remove" title="Remove this item">×</a>
                                    <a href="#">
                                        <img width="160" height="160" src="<?php echo THEMES_DEFAULT_URL?>/img/shop-item.png" alt="image">
                                        Shop Item 02
                                    </a>
                                                
                                    <span class="quantity">1 × <span class="woocommerce-Price-amount amount">
                                        <span class="woocommerce-Price-currencySymbol">$</span>70.00</span>
                                    </span>
                                </li>
                                <li class="mini_cart_item">
                                    <a href="#" class="remove" title="Remove this item">×</a>
                                    <a href="#">
                                        <img width="160" height="160" src="<?php echo THEMES_DEFAULT_URL?>/img/shop-item.png" alt="image">
                                        Shop Item 03
                                    </a>
                                                
                                    <span class="quantity">1 × <span class="woocommerce-Price-amount amount">
                                        <span class="woocommerce-Price-currencySymbol">$</span>30.00</span>
                                    </span>
                                </li>
                            </ul><!-- /.product_list_widget -->

                            <p class="total">
                                <strong>Subtotal:</strong>
                                <span class="woocommerce-Price-amount amount">
                                    <span class="woocommerce-Price-currencySymbol">$</span>300.00
                                </span>
                            </p>
        
                            <p class="buttons">
                                <a href="#" class="wprt-button small">View Cart</a>
                                <a href="#" class="wprt-button small checkout">Checkout</a>
                            </p>
                        </div>
                    </div>
                </div><!-- /.nav-top-cart-wrapper -->
            </div>
        </div><!-- /#site-header-inner -->
    </header><!-- /#site-header -->
</div><!-- /#site-header-wrap -->