<?php 
	// use NodejsPhpFallback\Uglify;
    $version = Zend_Registry::get('version');
?>

<!-- Theme Style -->
<link rel="stylesheet" type="text/css" href="<?php echo THEMES_DEFAULT_URL ?>css/style.css">

<!-- plugins -->
<link rel="stylesheet" href="<?php echo PLUGINS_URL ; ?>jquery.growl/css/jquery.growl.css"/>
<link rel="stylesheet" href="<?php echo PLUGINS_URL ; ?>ladda/css/ladda.min.css"/>
<link rel="stylesheet" href="<?php echo PLUGINS_URL ; ?>aos/aos.css"/>

<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/spacing-and-height.css" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom-bootstrap-margin-padding.css" type="text/css">
<link rel="stylesheet" href="<?php echo THEMES_DEFAULT_URL ?>css/custom.css?v=<?php echo $version; ?>" type="text/css">


<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
