<?php 
	// use NodejsPhpFallback\Uglify;
    $version = Zend_Registry::get('version');
?>

<!-- Javascript -->
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/animsition.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/plugins.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/countTo.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/fitText.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/flexslider.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/vegas.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/cube.portfolio.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/typed.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/main.js"></script>


<!-- Revolution Slider -->
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/jquery.themepunch.tools.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>js/rev-slider.js"></script>
<!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->  
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.actions.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.carousel.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.migration.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.navigation.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.parallax.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
<script type="text/javascript" src="<?php echo THEMES_DEFAULT_URL?>rev-slider/js/extensions/revolution.extension.video.min.js"></script>



<!-- plugins -->
<script src="<?php echo PLUGINS_URL ?>autosize.min.js"></script>
<script type='text/javascript' src='<?php echo PLUGINS_URL; ?>jquery.growl/js/jquery.growl.js'></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/spin.min.js" ></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>ladda/js/ladda.min.js" ></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>aos/aos.js" ></script>
<script type="text/javascript" src="<?php echo PLUGINS_URL; ?>initial.js" ></script>  

<!-- custom -->
<script src="<?php echo THEMES_DEFAULT_URL?>js/formvalidation.js?v=<?php echo $version?>"></script>
<script src="<?php echo THEMES_DEFAULT_URL?>js/app.js?v=<?php echo $version?>"></script>

<!-- fb customer chat -->
<script src="<?php echo THEMES_DEFAULT_URL?>js/xfbml.customerchat.js"></script>